// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: duox/agent/v1/agent.proto
// Protobuf Java Version: 4.27.2

package com.duox.dtunnel.grpc.pb;

public interface AgentMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:duox.agent.v1.AgentMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.duox.agent.v1.Hello hello = 1;</code>
   * @return Whether the hello field is set.
   */
  boolean hasHello();
  /**
   * <code>.duox.agent.v1.Hello hello = 1;</code>
   * @return The hello.
   */
  com.duox.dtunnel.grpc.pb.Hello getHello();
  /**
   * <code>.duox.agent.v1.Hello hello = 1;</code>
   */
  com.duox.dtunnel.grpc.pb.HelloOrBuilder getHelloOrBuilder();

  /**
   * <code>.duox.agent.v1.Heartbeat heartbeat = 2;</code>
   * @return Whether the heartbeat field is set.
   */
  boolean hasHeartbeat();
  /**
   * <code>.duox.agent.v1.Heartbeat heartbeat = 2;</code>
   * @return The heartbeat.
   */
  com.duox.dtunnel.grpc.pb.Heartbeat getHeartbeat();
  /**
   * <code>.duox.agent.v1.Heartbeat heartbeat = 2;</code>
   */
  com.duox.dtunnel.grpc.pb.HeartbeatOrBuilder getHeartbeatOrBuilder();

  com.duox.dtunnel.grpc.pb.AgentMessage.KindCase getKindCase();
}
