// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: duox/agent/v1/agent.proto
// Protobuf Java Version: 4.27.2

package com.duox.dtunnel.grpc.pb;

/**
 * <pre>
 * Agent -&gt; server on the Control stream.
 * </pre>
 *
 * Protobuf type {@code duox.agent.v1.AgentMessage}
 */
public final class AgentMessage extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:duox.agent.v1.AgentMessage)
    AgentMessageOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 27,
      /* patch= */ 2,
      /* suffix= */ "",
      AgentMessage.class.getName());
  }
  // Use AgentMessage.newBuilder() to construct.
  private AgentMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private AgentMessage() {
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.duox.dtunnel.grpc.pb.AgentProto.internal_static_duox_agent_v1_AgentMessage_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.duox.dtunnel.grpc.pb.AgentProto.internal_static_duox_agent_v1_AgentMessage_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.duox.dtunnel.grpc.pb.AgentMessage.class, com.duox.dtunnel.grpc.pb.AgentMessage.Builder.class);
  }

  private int kindCase_ = 0;
  @SuppressWarnings("serial")
  private java.lang.Object kind_;
  public enum KindCase
      implements com.google.protobuf.Internal.EnumLite,
          com.google.protobuf.AbstractMessage.InternalOneOfEnum {
    HELLO(1),
    HEARTBEAT(2),
    KIND_NOT_SET(0);
    private final int value;
    private KindCase(int value) {
      this.value = value;
    }
    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static KindCase valueOf(int value) {
      return forNumber(value);
    }

    public static KindCase forNumber(int value) {
      switch (value) {
        case 1: return HELLO;
        case 2: return HEARTBEAT;
        case 0: return KIND_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public KindCase
  getKindCase() {
    return KindCase.forNumber(
        kindCase_);
  }

  public static final int HELLO_FIELD_NUMBER = 1;
  /**
   * <code>.duox.agent.v1.Hello hello = 1;</code>
   * @return Whether the hello field is set.
   */
  @java.lang.Override
  public boolean hasHello() {
    return kindCase_ == 1;
  }
  /**
   * <code>.duox.agent.v1.Hello hello = 1;</code>
   * @return The hello.
   */
  @java.lang.Override
  public com.duox.dtunnel.grpc.pb.Hello getHello() {
    if (kindCase_ == 1) {
       return (com.duox.dtunnel.grpc.pb.Hello) kind_;
    }
    return com.duox.dtunnel.grpc.pb.Hello.getDefaultInstance();
  }
  /**
   * <code>.duox.agent.v1.Hello hello = 1;</code>
   */
  @java.lang.Override
  public com.duox.dtunnel.grpc.pb.HelloOrBuilder getHelloOrBuilder() {
    if (kindCase_ == 1) {
       return (com.duox.dtunnel.grpc.pb.Hello) kind_;
    }
    return com.duox.dtunnel.grpc.pb.Hello.getDefaultInstance();
  }

  public static final int HEARTBEAT_FIELD_NUMBER = 2;
  /**
   * <code>.duox.agent.v1.Heartbeat heartbeat = 2;</code>
   * @return Whether the heartbeat field is set.
   */
  @java.lang.Override
  public boolean hasHeartbeat() {
    return kindCase_ == 2;
  }
  /**
   * <code>.duox.agent.v1.Heartbeat heartbeat = 2;</code>
   * @return The heartbeat.
   */
  @java.lang.Override
  public com.duox.dtunnel.grpc.pb.Heartbeat getHeartbeat() {
    if (kindCase_ == 2) {
       return (com.duox.dtunnel.grpc.pb.Heartbeat) kind_;
    }
    return com.duox.dtunnel.grpc.pb.Heartbeat.getDefaultInstance();
  }
  /**
   * <code>.duox.agent.v1.Heartbeat heartbeat = 2;</code>
   */
  @java.lang.Override
  public com.duox.dtunnel.grpc.pb.HeartbeatOrBuilder getHeartbeatOrBuilder() {
    if (kindCase_ == 2) {
       return (com.duox.dtunnel.grpc.pb.Heartbeat) kind_;
    }
    return com.duox.dtunnel.grpc.pb.Heartbeat.getDefaultInstance();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (kindCase_ == 1) {
      output.writeMessage(1, (com.duox.dtunnel.grpc.pb.Hello) kind_);
    }
    if (kindCase_ == 2) {
      output.writeMessage(2, (com.duox.dtunnel.grpc.pb.Heartbeat) kind_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (kindCase_ == 1) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, (com.duox.dtunnel.grpc.pb.Hello) kind_);
    }
    if (kindCase_ == 2) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, (com.duox.dtunnel.grpc.pb.Heartbeat) kind_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.duox.dtunnel.grpc.pb.AgentMessage)) {
      return super.equals(obj);
    }
    com.duox.dtunnel.grpc.pb.AgentMessage other = (com.duox.dtunnel.grpc.pb.AgentMessage) obj;

    if (!getKindCase().equals(other.getKindCase())) return false;
    switch (kindCase_) {
      case 1:
        if (!getHello()
            .equals(other.getHello())) return false;
        break;
      case 2:
        if (!getHeartbeat()
            .equals(other.getHeartbeat())) return false;
        break;
      case 0:
      default:
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    switch (kindCase_) {
      case 1:
        hash = (37 * hash) + HELLO_FIELD_NUMBER;
        hash = (53 * hash) + getHello().hashCode();
        break;
      case 2:
        hash = (37 * hash) + HEARTBEAT_FIELD_NUMBER;
        hash = (53 * hash) + getHeartbeat().hashCode();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.duox.dtunnel.grpc.pb.AgentMessage parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.duox.dtunnel.grpc.pb.AgentMessage parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.duox.dtunnel.grpc.pb.AgentMessage parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.duox.dtunnel.grpc.pb.AgentMessage parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.duox.dtunnel.grpc.pb.AgentMessage parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.duox.dtunnel.grpc.pb.AgentMessage parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.duox.dtunnel.grpc.pb.AgentMessage parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.duox.dtunnel.grpc.pb.AgentMessage parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.duox.dtunnel.grpc.pb.AgentMessage parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.duox.dtunnel.grpc.pb.AgentMessage parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.duox.dtunnel.grpc.pb.AgentMessage parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.duox.dtunnel.grpc.pb.AgentMessage parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.duox.dtunnel.grpc.pb.AgentMessage prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Agent -&gt; server on the Control stream.
   * </pre>
   *
   * Protobuf type {@code duox.agent.v1.AgentMessage}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:duox.agent.v1.AgentMessage)
      com.duox.dtunnel.grpc.pb.AgentMessageOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.duox.dtunnel.grpc.pb.AgentProto.internal_static_duox_agent_v1_AgentMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.duox.dtunnel.grpc.pb.AgentProto.internal_static_duox_agent_v1_AgentMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.duox.dtunnel.grpc.pb.AgentMessage.class, com.duox.dtunnel.grpc.pb.AgentMessage.Builder.class);
    }

    // Construct using com.duox.dtunnel.grpc.pb.AgentMessage.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (helloBuilder_ != null) {
        helloBuilder_.clear();
      }
      if (heartbeatBuilder_ != null) {
        heartbeatBuilder_.clear();
      }
      kindCase_ = 0;
      kind_ = null;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.duox.dtunnel.grpc.pb.AgentProto.internal_static_duox_agent_v1_AgentMessage_descriptor;
    }

    @java.lang.Override
    public com.duox.dtunnel.grpc.pb.AgentMessage getDefaultInstanceForType() {
      return com.duox.dtunnel.grpc.pb.AgentMessage.getDefaultInstance();
    }

    @java.lang.Override
    public com.duox.dtunnel.grpc.pb.AgentMessage build() {
      com.duox.dtunnel.grpc.pb.AgentMessage result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.duox.dtunnel.grpc.pb.AgentMessage buildPartial() {
      com.duox.dtunnel.grpc.pb.AgentMessage result = new com.duox.dtunnel.grpc.pb.AgentMessage(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      buildPartialOneofs(result);
      onBuilt();
      return result;
    }

    private void buildPartial0(com.duox.dtunnel.grpc.pb.AgentMessage result) {
      int from_bitField0_ = bitField0_;
    }

    private void buildPartialOneofs(com.duox.dtunnel.grpc.pb.AgentMessage result) {
      result.kindCase_ = kindCase_;
      result.kind_ = this.kind_;
      if (kindCase_ == 1 &&
          helloBuilder_ != null) {
        result.kind_ = helloBuilder_.build();
      }
      if (kindCase_ == 2 &&
          heartbeatBuilder_ != null) {
        result.kind_ = heartbeatBuilder_.build();
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.duox.dtunnel.grpc.pb.AgentMessage) {
        return mergeFrom((com.duox.dtunnel.grpc.pb.AgentMessage)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.duox.dtunnel.grpc.pb.AgentMessage other) {
      if (other == com.duox.dtunnel.grpc.pb.AgentMessage.getDefaultInstance()) return this;
      switch (other.getKindCase()) {
        case HELLO: {
          mergeHello(other.getHello());
          break;
        }
        case HEARTBEAT: {
          mergeHeartbeat(other.getHeartbeat());
          break;
        }
        case KIND_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  getHelloFieldBuilder().getBuilder(),
                  extensionRegistry);
              kindCase_ = 1;
              break;
            } // case 10
            case 18: {
              input.readMessage(
                  getHeartbeatFieldBuilder().getBuilder(),
                  extensionRegistry);
              kindCase_ = 2;
              break;
            } // case 18
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int kindCase_ = 0;
    private java.lang.Object kind_;
    public KindCase
        getKindCase() {
      return KindCase.forNumber(
          kindCase_);
    }

    public Builder clearKind() {
      kindCase_ = 0;
      kind_ = null;
      onChanged();
      return this;
    }

    private int bitField0_;

    private com.google.protobuf.SingleFieldBuilder<
        com.duox.dtunnel.grpc.pb.Hello, com.duox.dtunnel.grpc.pb.Hello.Builder, com.duox.dtunnel.grpc.pb.HelloOrBuilder> helloBuilder_;
    /**
     * <code>.duox.agent.v1.Hello hello = 1;</code>
     * @return Whether the hello field is set.
     */
    @java.lang.Override
    public boolean hasHello() {
      return kindCase_ == 1;
    }
    /**
     * <code>.duox.agent.v1.Hello hello = 1;</code>
     * @return The hello.
     */
    @java.lang.Override
    public com.duox.dtunnel.grpc.pb.Hello getHello() {
      if (helloBuilder_ == null) {
        if (kindCase_ == 1) {
          return (com.duox.dtunnel.grpc.pb.Hello) kind_;
        }
        return com.duox.dtunnel.grpc.pb.Hello.getDefaultInstance();
      } else {
        if (kindCase_ == 1) {
          return helloBuilder_.getMessage();
        }
        return com.duox.dtunnel.grpc.pb.Hello.getDefaultInstance();
      }
    }
    /**
     * <code>.duox.agent.v1.Hello hello = 1;</code>
     */
    public Builder setHello(com.duox.dtunnel.grpc.pb.Hello value) {
      if (helloBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        kind_ = value;
        onChanged();
      } else {
        helloBuilder_.setMessage(value);
      }
      kindCase_ = 1;
      return this;
    }
    /**
     * <code>.duox.agent.v1.Hello hello = 1;</code>
     */
    public Builder setHello(
        com.duox.dtunnel.grpc.pb.Hello.Builder builderForValue) {
      if (helloBuilder_ == null) {
        kind_ = builderForValue.build();
        onChanged();
      } else {
        helloBuilder_.setMessage(builderForValue.build());
      }
      kindCase_ = 1;
      return this;
    }
    /**
     * <code>.duox.agent.v1.Hello hello = 1;</code>
     */
    public Builder mergeHello(com.duox.dtunnel.grpc.pb.Hello value) {
      if (helloBuilder_ == null) {
        if (kindCase_ == 1 &&
            kind_ != com.duox.dtunnel.grpc.pb.Hello.getDefaultInstance()) {
          kind_ = com.duox.dtunnel.grpc.pb.Hello.newBuilder((com.duox.dtunnel.grpc.pb.Hello) kind_)
              .mergeFrom(value).buildPartial();
        } else {
          kind_ = value;
        }
        onChanged();
      } else {
        if (kindCase_ == 1) {
          helloBuilder_.mergeFrom(value);
        } else {
          helloBuilder_.setMessage(value);
        }
      }
      kindCase_ = 1;
      return this;
    }
    /**
     * <code>.duox.agent.v1.Hello hello = 1;</code>
     */
    public Builder clearHello() {
      if (helloBuilder_ == null) {
        if (kindCase_ == 1) {
          kindCase_ = 0;
          kind_ = null;
          onChanged();
        }
      } else {
        if (kindCase_ == 1) {
          kindCase_ = 0;
          kind_ = null;
        }
        helloBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.duox.agent.v1.Hello hello = 1;</code>
     */
    public com.duox.dtunnel.grpc.pb.Hello.Builder getHelloBuilder() {
      return getHelloFieldBuilder().getBuilder();
    }
    /**
     * <code>.duox.agent.v1.Hello hello = 1;</code>
     */
    @java.lang.Override
    public com.duox.dtunnel.grpc.pb.HelloOrBuilder getHelloOrBuilder() {
      if ((kindCase_ == 1) && (helloBuilder_ != null)) {
        return helloBuilder_.getMessageOrBuilder();
      } else {
        if (kindCase_ == 1) {
          return (com.duox.dtunnel.grpc.pb.Hello) kind_;
        }
        return com.duox.dtunnel.grpc.pb.Hello.getDefaultInstance();
      }
    }
    /**
     * <code>.duox.agent.v1.Hello hello = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.duox.dtunnel.grpc.pb.Hello, com.duox.dtunnel.grpc.pb.Hello.Builder, com.duox.dtunnel.grpc.pb.HelloOrBuilder> 
        getHelloFieldBuilder() {
      if (helloBuilder_ == null) {
        if (!(kindCase_ == 1)) {
          kind_ = com.duox.dtunnel.grpc.pb.Hello.getDefaultInstance();
        }
        helloBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.duox.dtunnel.grpc.pb.Hello, com.duox.dtunnel.grpc.pb.Hello.Builder, com.duox.dtunnel.grpc.pb.HelloOrBuilder>(
                (com.duox.dtunnel.grpc.pb.Hello) kind_,
                getParentForChildren(),
                isClean());
        kind_ = null;
      }
      kindCase_ = 1;
      onChanged();
      return helloBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilder<
        com.duox.dtunnel.grpc.pb.Heartbeat, com.duox.dtunnel.grpc.pb.Heartbeat.Builder, com.duox.dtunnel.grpc.pb.HeartbeatOrBuilder> heartbeatBuilder_;
    /**
     * <code>.duox.agent.v1.Heartbeat heartbeat = 2;</code>
     * @return Whether the heartbeat field is set.
     */
    @java.lang.Override
    public boolean hasHeartbeat() {
      return kindCase_ == 2;
    }
    /**
     * <code>.duox.agent.v1.Heartbeat heartbeat = 2;</code>
     * @return The heartbeat.
     */
    @java.lang.Override
    public com.duox.dtunnel.grpc.pb.Heartbeat getHeartbeat() {
      if (heartbeatBuilder_ == null) {
        if (kindCase_ == 2) {
          return (com.duox.dtunnel.grpc.pb.Heartbeat) kind_;
        }
        return com.duox.dtunnel.grpc.pb.Heartbeat.getDefaultInstance();
      } else {
        if (kindCase_ == 2) {
          return heartbeatBuilder_.getMessage();
        }
        return com.duox.dtunnel.grpc.pb.Heartbeat.getDefaultInstance();
      }
    }
    /**
     * <code>.duox.agent.v1.Heartbeat heartbeat = 2;</code>
     */
    public Builder setHeartbeat(com.duox.dtunnel.grpc.pb.Heartbeat value) {
      if (heartbeatBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        kind_ = value;
        onChanged();
      } else {
        heartbeatBuilder_.setMessage(value);
      }
      kindCase_ = 2;
      return this;
    }
    /**
     * <code>.duox.agent.v1.Heartbeat heartbeat = 2;</code>
     */
    public Builder setHeartbeat(
        com.duox.dtunnel.grpc.pb.Heartbeat.Builder builderForValue) {
      if (heartbeatBuilder_ == null) {
        kind_ = builderForValue.build();
        onChanged();
      } else {
        heartbeatBuilder_.setMessage(builderForValue.build());
      }
      kindCase_ = 2;
      return this;
    }
    /**
     * <code>.duox.agent.v1.Heartbeat heartbeat = 2;</code>
     */
    public Builder mergeHeartbeat(com.duox.dtunnel.grpc.pb.Heartbeat value) {
      if (heartbeatBuilder_ == null) {
        if (kindCase_ == 2 &&
            kind_ != com.duox.dtunnel.grpc.pb.Heartbeat.getDefaultInstance()) {
          kind_ = com.duox.dtunnel.grpc.pb.Heartbeat.newBuilder((com.duox.dtunnel.grpc.pb.Heartbeat) kind_)
              .mergeFrom(value).buildPartial();
        } else {
          kind_ = value;
        }
        onChanged();
      } else {
        if (kindCase_ == 2) {
          heartbeatBuilder_.mergeFrom(value);
        } else {
          heartbeatBuilder_.setMessage(value);
        }
      }
      kindCase_ = 2;
      return this;
    }
    /**
     * <code>.duox.agent.v1.Heartbeat heartbeat = 2;</code>
     */
    public Builder clearHeartbeat() {
      if (heartbeatBuilder_ == null) {
        if (kindCase_ == 2) {
          kindCase_ = 0;
          kind_ = null;
          onChanged();
        }
      } else {
        if (kindCase_ == 2) {
          kindCase_ = 0;
          kind_ = null;
        }
        heartbeatBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.duox.agent.v1.Heartbeat heartbeat = 2;</code>
     */
    public com.duox.dtunnel.grpc.pb.Heartbeat.Builder getHeartbeatBuilder() {
      return getHeartbeatFieldBuilder().getBuilder();
    }
    /**
     * <code>.duox.agent.v1.Heartbeat heartbeat = 2;</code>
     */
    @java.lang.Override
    public com.duox.dtunnel.grpc.pb.HeartbeatOrBuilder getHeartbeatOrBuilder() {
      if ((kindCase_ == 2) && (heartbeatBuilder_ != null)) {
        return heartbeatBuilder_.getMessageOrBuilder();
      } else {
        if (kindCase_ == 2) {
          return (com.duox.dtunnel.grpc.pb.Heartbeat) kind_;
        }
        return com.duox.dtunnel.grpc.pb.Heartbeat.getDefaultInstance();
      }
    }
    /**
     * <code>.duox.agent.v1.Heartbeat heartbeat = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.duox.dtunnel.grpc.pb.Heartbeat, com.duox.dtunnel.grpc.pb.Heartbeat.Builder, com.duox.dtunnel.grpc.pb.HeartbeatOrBuilder> 
        getHeartbeatFieldBuilder() {
      if (heartbeatBuilder_ == null) {
        if (!(kindCase_ == 2)) {
          kind_ = com.duox.dtunnel.grpc.pb.Heartbeat.getDefaultInstance();
        }
        heartbeatBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.duox.dtunnel.grpc.pb.Heartbeat, com.duox.dtunnel.grpc.pb.Heartbeat.Builder, com.duox.dtunnel.grpc.pb.HeartbeatOrBuilder>(
                (com.duox.dtunnel.grpc.pb.Heartbeat) kind_,
                getParentForChildren(),
                isClean());
        kind_ = null;
      }
      kindCase_ = 2;
      onChanged();
      return heartbeatBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:duox.agent.v1.AgentMessage)
  }

  // @@protoc_insertion_point(class_scope:duox.agent.v1.AgentMessage)
  private static final com.duox.dtunnel.grpc.pb.AgentMessage DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.duox.dtunnel.grpc.pb.AgentMessage();
  }

  public static com.duox.dtunnel.grpc.pb.AgentMessage getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<AgentMessage>
      PARSER = new com.google.protobuf.AbstractParser<AgentMessage>() {
    @java.lang.Override
    public AgentMessage parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<AgentMessage> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<AgentMessage> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.duox.dtunnel.grpc.pb.AgentMessage getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

