// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: duox/agent/v1/agent.proto
// Protobuf Java Version: 4.27.2

package com.duox.dtunnel.grpc.pb;

public final class AgentProto {
  private AgentProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 27,
      /* patch= */ 2,
      /* suffix= */ "",
      AgentProto.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_duox_agent_v1_RegisterRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_duox_agent_v1_RegisterRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_duox_agent_v1_RegisterResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_duox_agent_v1_RegisterResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_duox_agent_v1_AgentMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_duox_agent_v1_AgentMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_duox_agent_v1_Hello_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_duox_agent_v1_Hello_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_duox_agent_v1_Heartbeat_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_duox_agent_v1_Heartbeat_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_duox_agent_v1_TunnelReport_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_duox_agent_v1_TunnelReport_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_duox_agent_v1_ServerMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_duox_agent_v1_ServerMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_duox_agent_v1_ConfigPush_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_duox_agent_v1_ConfigPush_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_duox_agent_v1_Proxy_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_duox_agent_v1_Proxy_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_duox_agent_v1_Revoked_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_duox_agent_v1_Revoked_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_duox_agent_v1_HeartbeatAck_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_duox_agent_v1_HeartbeatAck_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\031duox/agent/v1/agent.proto\022\rduox.agent." +
      "v1\"o\n\017RegisterRequest\022\r\n\005email\030\001 \001(\t\022\020\n\010" +
      "password\030\002 \001(\t\022\022\n\npublic_key\030\003 \001(\t\022\020\n\010pl" +
      "atform\030\004 \001(\t\022\025\n\ragent_version\030\005 \001(\t\"C\n\020R" +
      "egisterResponse\022\020\n\010agent_id\030\001 \001(\t\022\r\n\005tok" +
      "en\030\002 \001(\t\022\016\n\006status\030\003 \001(\t\"l\n\014AgentMessage" +
      "\022%\n\005hello\030\001 \001(\0132\024.duox.agent.v1.HelloH\000\022" +
      "-\n\theartbeat\030\002 \001(\0132\030.duox.agent.v1.Heart" +
      "beatH\000B\006\n\004kind\"F\n\005Hello\022\r\n\005token\030\001 \001(\t\022\025" +
      "\n\ragent_version\030\002 \001(\t\022\027\n\017applied_version" +
      "\030\003 \001(\005\"i\n\tHeartbeat\022\027\n\017applied_version\030\001" +
      " \001(\005\022\025\n\ragent_version\030\002 \001(\t\022,\n\007tunnels\030\003" +
      " \003(\0132\033.duox.agent.v1.TunnelReport\"1\n\014Tun" +
      "nelReport\022\021\n\ttunnel_id\030\001 \001(\t\022\016\n\006status\030\002" +
      " \001(\t\"\233\001\n\rServerMessage\022+\n\006config\030\001 \001(\0132\031" +
      ".duox.agent.v1.ConfigPushH\000\022)\n\007revoked\030\002" +
      " \001(\0132\026.duox.agent.v1.RevokedH\000\022*\n\003ack\030\003 " +
      "\001(\0132\033.duox.agent.v1.HeartbeatAckH\000B\006\n\004ki" +
      "nd\"D\n\nConfigPush\022\017\n\007version\030\001 \001(\005\022%\n\007pro" +
      "xies\030\002 \003(\0132\024.duox.agent.v1.Proxy\"\313\001\n\005Pro" +
      "xy\022\021\n\ttunnel_id\030\001 \001(\t\022\014\n\004name\030\002 \001(\t\022\014\n\004t" +
      "ype\030\003 \001(\t\022\023\n\013server_addr\030\004 \001(\t\022\023\n\013server" +
      "_port\030\005 \001(\005\022\023\n\013remote_port\030\006 \001(\005\022\016\n\006doma" +
      "in\030\007 \001(\t\022\022\n\nlocal_host\030\010 \001(\t\022\022\n\nlocal_po" +
      "rt\030\t \001(\005\022\034\n\024bandwidth_limit_mbps\030\n \001(\005\"\031" +
      "\n\007Revoked\022\016\n\006reason\030\001 \001(\t\"\'\n\014HeartbeatAc" +
      "k\022\027\n\017desired_version\030\001 \001(\0052\245\001\n\014AgentServ" +
      "ice\022K\n\010Register\022\036.duox.agent.v1.Register" +
      "Request\032\037.duox.agent.v1.RegisterResponse" +
      "\022H\n\007Control\022\033.duox.agent.v1.AgentMessage" +
      "\032\034.duox.agent.v1.ServerMessage(\0010\001BU\n\030co" +
      "m.duox.dtunnel.grpc.pbB\nAgentProtoP\001Z+gi" +
      "thub.com/duox/dtunnel-agent/control/pb;p" +
      "bb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_duox_agent_v1_RegisterRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_duox_agent_v1_RegisterRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_duox_agent_v1_RegisterRequest_descriptor,
        new java.lang.String[] { "Email", "Password", "PublicKey", "Platform", "AgentVersion", });
    internal_static_duox_agent_v1_RegisterResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_duox_agent_v1_RegisterResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_duox_agent_v1_RegisterResponse_descriptor,
        new java.lang.String[] { "AgentId", "Token", "Status", });
    internal_static_duox_agent_v1_AgentMessage_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_duox_agent_v1_AgentMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_duox_agent_v1_AgentMessage_descriptor,
        new java.lang.String[] { "Hello", "Heartbeat", "Kind", });
    internal_static_duox_agent_v1_Hello_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_duox_agent_v1_Hello_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_duox_agent_v1_Hello_descriptor,
        new java.lang.String[] { "Token", "AgentVersion", "AppliedVersion", });
    internal_static_duox_agent_v1_Heartbeat_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_duox_agent_v1_Heartbeat_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_duox_agent_v1_Heartbeat_descriptor,
        new java.lang.String[] { "AppliedVersion", "AgentVersion", "Tunnels", });
    internal_static_duox_agent_v1_TunnelReport_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_duox_agent_v1_TunnelReport_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_duox_agent_v1_TunnelReport_descriptor,
        new java.lang.String[] { "TunnelId", "Status", });
    internal_static_duox_agent_v1_ServerMessage_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_duox_agent_v1_ServerMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_duox_agent_v1_ServerMessage_descriptor,
        new java.lang.String[] { "Config", "Revoked", "Ack", "Kind", });
    internal_static_duox_agent_v1_ConfigPush_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_duox_agent_v1_ConfigPush_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_duox_agent_v1_ConfigPush_descriptor,
        new java.lang.String[] { "Version", "Proxies", });
    internal_static_duox_agent_v1_Proxy_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_duox_agent_v1_Proxy_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_duox_agent_v1_Proxy_descriptor,
        new java.lang.String[] { "TunnelId", "Name", "Type", "ServerAddr", "ServerPort", "RemotePort", "Domain", "LocalHost", "LocalPort", "BandwidthLimitMbps", });
    internal_static_duox_agent_v1_Revoked_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_duox_agent_v1_Revoked_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_duox_agent_v1_Revoked_descriptor,
        new java.lang.String[] { "Reason", });
    internal_static_duox_agent_v1_HeartbeatAck_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_duox_agent_v1_HeartbeatAck_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_duox_agent_v1_HeartbeatAck_descriptor,
        new java.lang.String[] { "DesiredVersion", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
