// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: duox/agent/v1/agent.proto
// Protobuf Java Version: 4.27.2

package com.duox.dtunnel.grpc.pb;

public interface ConfigPushOrBuilder extends
    // @@protoc_insertion_point(interface_extends:duox.agent.v1.ConfigPush)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 version = 1;</code>
   * @return The version.
   */
  int getVersion();

  /**
   * <code>repeated .duox.agent.v1.Proxy proxies = 2;</code>
   */
  java.util.List<com.duox.dtunnel.grpc.pb.Proxy> 
      getProxiesList();
  /**
   * <code>repeated .duox.agent.v1.Proxy proxies = 2;</code>
   */
  com.duox.dtunnel.grpc.pb.Proxy getProxies(int index);
  /**
   * <code>repeated .duox.agent.v1.Proxy proxies = 2;</code>
   */
  int getProxiesCount();
  /**
   * <code>repeated .duox.agent.v1.Proxy proxies = 2;</code>
   */
  java.util.List<? extends com.duox.dtunnel.grpc.pb.ProxyOrBuilder> 
      getProxiesOrBuilderList();
  /**
   * <code>repeated .duox.agent.v1.Proxy proxies = 2;</code>
   */
  com.duox.dtunnel.grpc.pb.ProxyOrBuilder getProxiesOrBuilder(
      int index);
}
