// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: duox/agent/v1/agent.proto
// Protobuf Java Version: 4.27.2

package com.duox.dtunnel.grpc.pb;

/**
 * Protobuf type {@code duox.agent.v1.ConfigPush}
 */
public final class ConfigPush extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:duox.agent.v1.ConfigPush)
    ConfigPushOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 27,
      /* patch= */ 2,
      /* suffix= */ "",
      ConfigPush.class.getName());
  }
  // Use ConfigPush.newBuilder() to construct.
  private ConfigPush(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private ConfigPush() {
    proxies_ = java.util.Collections.emptyList();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.duox.dtunnel.grpc.pb.AgentProto.internal_static_duox_agent_v1_ConfigPush_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.duox.dtunnel.grpc.pb.AgentProto.internal_static_duox_agent_v1_ConfigPush_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.duox.dtunnel.grpc.pb.ConfigPush.class, com.duox.dtunnel.grpc.pb.ConfigPush.Builder.class);
  }

  public static final int VERSION_FIELD_NUMBER = 1;
  private int version_ = 0;
  /**
   * <code>int32 version = 1;</code>
   * @return The version.
   */
  @java.lang.Override
  public int getVersion() {
    return version_;
  }

  public static final int PROXIES_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private java.util.List<com.duox.dtunnel.grpc.pb.Proxy> proxies_;
  /**
   * <code>repeated .duox.agent.v1.Proxy proxies = 2;</code>
   */
  @java.lang.Override
  public java.util.List<com.duox.dtunnel.grpc.pb.Proxy> getProxiesList() {
    return proxies_;
  }
  /**
   * <code>repeated .duox.agent.v1.Proxy proxies = 2;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.duox.dtunnel.grpc.pb.ProxyOrBuilder> 
      getProxiesOrBuilderList() {
    return proxies_;
  }
  /**
   * <code>repeated .duox.agent.v1.Proxy proxies = 2;</code>
   */
  @java.lang.Override
  public int getProxiesCount() {
    return proxies_.size();
  }
  /**
   * <code>repeated .duox.agent.v1.Proxy proxies = 2;</code>
   */
  @java.lang.Override
  public com.duox.dtunnel.grpc.pb.Proxy getProxies(int index) {
    return proxies_.get(index);
  }
  /**
   * <code>repeated .duox.agent.v1.Proxy proxies = 2;</code>
   */
  @java.lang.Override
  public com.duox.dtunnel.grpc.pb.ProxyOrBuilder getProxiesOrBuilder(
      int index) {
    return proxies_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (version_ != 0) {
      output.writeInt32(1, version_);
    }
    for (int i = 0; i < proxies_.size(); i++) {
      output.writeMessage(2, proxies_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (version_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, version_);
    }
    for (int i = 0; i < proxies_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, proxies_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.duox.dtunnel.grpc.pb.ConfigPush)) {
      return super.equals(obj);
    }
    com.duox.dtunnel.grpc.pb.ConfigPush other = (com.duox.dtunnel.grpc.pb.ConfigPush) obj;

    if (getVersion()
        != other.getVersion()) return false;
    if (!getProxiesList()
        .equals(other.getProxiesList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + VERSION_FIELD_NUMBER;
    hash = (53 * hash) + getVersion();
    if (getProxiesCount() > 0) {
      hash = (37 * hash) + PROXIES_FIELD_NUMBER;
      hash = (53 * hash) + getProxiesList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.duox.dtunnel.grpc.pb.ConfigPush parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.duox.dtunnel.grpc.pb.ConfigPush parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.duox.dtunnel.grpc.pb.ConfigPush parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.duox.dtunnel.grpc.pb.ConfigPush parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.duox.dtunnel.grpc.pb.ConfigPush parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.duox.dtunnel.grpc.pb.ConfigPush parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.duox.dtunnel.grpc.pb.ConfigPush parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.duox.dtunnel.grpc.pb.ConfigPush parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.duox.dtunnel.grpc.pb.ConfigPush parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.duox.dtunnel.grpc.pb.ConfigPush parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.duox.dtunnel.grpc.pb.ConfigPush parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.duox.dtunnel.grpc.pb.ConfigPush parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.duox.dtunnel.grpc.pb.ConfigPush prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code duox.agent.v1.ConfigPush}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:duox.agent.v1.ConfigPush)
      com.duox.dtunnel.grpc.pb.ConfigPushOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.duox.dtunnel.grpc.pb.AgentProto.internal_static_duox_agent_v1_ConfigPush_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.duox.dtunnel.grpc.pb.AgentProto.internal_static_duox_agent_v1_ConfigPush_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.duox.dtunnel.grpc.pb.ConfigPush.class, com.duox.dtunnel.grpc.pb.ConfigPush.Builder.class);
    }

    // Construct using com.duox.dtunnel.grpc.pb.ConfigPush.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      version_ = 0;
      if (proxiesBuilder_ == null) {
        proxies_ = java.util.Collections.emptyList();
      } else {
        proxies_ = null;
        proxiesBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000002);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.duox.dtunnel.grpc.pb.AgentProto.internal_static_duox_agent_v1_ConfigPush_descriptor;
    }

    @java.lang.Override
    public com.duox.dtunnel.grpc.pb.ConfigPush getDefaultInstanceForType() {
      return com.duox.dtunnel.grpc.pb.ConfigPush.getDefaultInstance();
    }

    @java.lang.Override
    public com.duox.dtunnel.grpc.pb.ConfigPush build() {
      com.duox.dtunnel.grpc.pb.ConfigPush result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.duox.dtunnel.grpc.pb.ConfigPush buildPartial() {
      com.duox.dtunnel.grpc.pb.ConfigPush result = new com.duox.dtunnel.grpc.pb.ConfigPush(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(com.duox.dtunnel.grpc.pb.ConfigPush result) {
      if (proxiesBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0)) {
          proxies_ = java.util.Collections.unmodifiableList(proxies_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.proxies_ = proxies_;
      } else {
        result.proxies_ = proxiesBuilder_.build();
      }
    }

    private void buildPartial0(com.duox.dtunnel.grpc.pb.ConfigPush result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.version_ = version_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.duox.dtunnel.grpc.pb.ConfigPush) {
        return mergeFrom((com.duox.dtunnel.grpc.pb.ConfigPush)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.duox.dtunnel.grpc.pb.ConfigPush other) {
      if (other == com.duox.dtunnel.grpc.pb.ConfigPush.getDefaultInstance()) return this;
      if (other.getVersion() != 0) {
        setVersion(other.getVersion());
      }
      if (proxiesBuilder_ == null) {
        if (!other.proxies_.isEmpty()) {
          if (proxies_.isEmpty()) {
            proxies_ = other.proxies_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureProxiesIsMutable();
            proxies_.addAll(other.proxies_);
          }
          onChanged();
        }
      } else {
        if (!other.proxies_.isEmpty()) {
          if (proxiesBuilder_.isEmpty()) {
            proxiesBuilder_.dispose();
            proxiesBuilder_ = null;
            proxies_ = other.proxies_;
            bitField0_ = (bitField0_ & ~0x00000002);
            proxiesBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 getProxiesFieldBuilder() : null;
          } else {
            proxiesBuilder_.addAllMessages(other.proxies_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              version_ = input.readInt32();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 18: {
              com.duox.dtunnel.grpc.pb.Proxy m =
                  input.readMessage(
                      com.duox.dtunnel.grpc.pb.Proxy.parser(),
                      extensionRegistry);
              if (proxiesBuilder_ == null) {
                ensureProxiesIsMutable();
                proxies_.add(m);
              } else {
                proxiesBuilder_.addMessage(m);
              }
              break;
            } // case 18
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int version_ ;
    /**
     * <code>int32 version = 1;</code>
     * @return The version.
     */
    @java.lang.Override
    public int getVersion() {
      return version_;
    }
    /**
     * <code>int32 version = 1;</code>
     * @param value The version to set.
     * @return This builder for chaining.
     */
    public Builder setVersion(int value) {

      version_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>int32 version = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearVersion() {
      bitField0_ = (bitField0_ & ~0x00000001);
      version_ = 0;
      onChanged();
      return this;
    }

    private java.util.List<com.duox.dtunnel.grpc.pb.Proxy> proxies_ =
      java.util.Collections.emptyList();
    private void ensureProxiesIsMutable() {
      if (!((bitField0_ & 0x00000002) != 0)) {
        proxies_ = new java.util.ArrayList<com.duox.dtunnel.grpc.pb.Proxy>(proxies_);
        bitField0_ |= 0x00000002;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        com.duox.dtunnel.grpc.pb.Proxy, com.duox.dtunnel.grpc.pb.Proxy.Builder, com.duox.dtunnel.grpc.pb.ProxyOrBuilder> proxiesBuilder_;

    /**
     * <code>repeated .duox.agent.v1.Proxy proxies = 2;</code>
     */
    public java.util.List<com.duox.dtunnel.grpc.pb.Proxy> getProxiesList() {
      if (proxiesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(proxies_);
      } else {
        return proxiesBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .duox.agent.v1.Proxy proxies = 2;</code>
     */
    public int getProxiesCount() {
      if (proxiesBuilder_ == null) {
        return proxies_.size();
      } else {
        return proxiesBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .duox.agent.v1.Proxy proxies = 2;</code>
     */
    public com.duox.dtunnel.grpc.pb.Proxy getProxies(int index) {
      if (proxiesBuilder_ == null) {
        return proxies_.get(index);
      } else {
        return proxiesBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .duox.agent.v1.Proxy proxies = 2;</code>
     */
    public Builder setProxies(
        int index, com.duox.dtunnel.grpc.pb.Proxy value) {
      if (proxiesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureProxiesIsMutable();
        proxies_.set(index, value);
        onChanged();
      } else {
        proxiesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .duox.agent.v1.Proxy proxies = 2;</code>
     */
    public Builder setProxies(
        int index, com.duox.dtunnel.grpc.pb.Proxy.Builder builderForValue) {
      if (proxiesBuilder_ == null) {
        ensureProxiesIsMutable();
        proxies_.set(index, builderForValue.build());
        onChanged();
      } else {
        proxiesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .duox.agent.v1.Proxy proxies = 2;</code>
     */
    public Builder addProxies(com.duox.dtunnel.grpc.pb.Proxy value) {
      if (proxiesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureProxiesIsMutable();
        proxies_.add(value);
        onChanged();
      } else {
        proxiesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .duox.agent.v1.Proxy proxies = 2;</code>
     */
    public Builder addProxies(
        int index, com.duox.dtunnel.grpc.pb.Proxy value) {
      if (proxiesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureProxiesIsMutable();
        proxies_.add(index, value);
        onChanged();
      } else {
        proxiesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .duox.agent.v1.Proxy proxies = 2;</code>
     */
    public Builder addProxies(
        com.duox.dtunnel.grpc.pb.Proxy.Builder builderForValue) {
      if (proxiesBuilder_ == null) {
        ensureProxiesIsMutable();
        proxies_.add(builderForValue.build());
        onChanged();
      } else {
        proxiesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .duox.agent.v1.Proxy proxies = 2;</code>
     */
    public Builder addProxies(
        int index, com.duox.dtunnel.grpc.pb.Proxy.Builder builderForValue) {
      if (proxiesBuilder_ == null) {
        ensureProxiesIsMutable();
        proxies_.add(index, builderForValue.build());
        onChanged();
      } else {
        proxiesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .duox.agent.v1.Proxy proxies = 2;</code>
     */
    public Builder addAllProxies(
        java.lang.Iterable<? extends com.duox.dtunnel.grpc.pb.Proxy> values) {
      if (proxiesBuilder_ == null) {
        ensureProxiesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, proxies_);
        onChanged();
      } else {
        proxiesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .duox.agent.v1.Proxy proxies = 2;</code>
     */
    public Builder clearProxies() {
      if (proxiesBuilder_ == null) {
        proxies_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        proxiesBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .duox.agent.v1.Proxy proxies = 2;</code>
     */
    public Builder removeProxies(int index) {
      if (proxiesBuilder_ == null) {
        ensureProxiesIsMutable();
        proxies_.remove(index);
        onChanged();
      } else {
        proxiesBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .duox.agent.v1.Proxy proxies = 2;</code>
     */
    public com.duox.dtunnel.grpc.pb.Proxy.Builder getProxiesBuilder(
        int index) {
      return getProxiesFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .duox.agent.v1.Proxy proxies = 2;</code>
     */
    public com.duox.dtunnel.grpc.pb.ProxyOrBuilder getProxiesOrBuilder(
        int index) {
      if (proxiesBuilder_ == null) {
        return proxies_.get(index);  } else {
        return proxiesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .duox.agent.v1.Proxy proxies = 2;</code>
     */
    public java.util.List<? extends com.duox.dtunnel.grpc.pb.ProxyOrBuilder> 
         getProxiesOrBuilderList() {
      if (proxiesBuilder_ != null) {
        return proxiesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(proxies_);
      }
    }
    /**
     * <code>repeated .duox.agent.v1.Proxy proxies = 2;</code>
     */
    public com.duox.dtunnel.grpc.pb.Proxy.Builder addProxiesBuilder() {
      return getProxiesFieldBuilder().addBuilder(
          com.duox.dtunnel.grpc.pb.Proxy.getDefaultInstance());
    }
    /**
     * <code>repeated .duox.agent.v1.Proxy proxies = 2;</code>
     */
    public com.duox.dtunnel.grpc.pb.Proxy.Builder addProxiesBuilder(
        int index) {
      return getProxiesFieldBuilder().addBuilder(
          index, com.duox.dtunnel.grpc.pb.Proxy.getDefaultInstance());
    }
    /**
     * <code>repeated .duox.agent.v1.Proxy proxies = 2;</code>
     */
    public java.util.List<com.duox.dtunnel.grpc.pb.Proxy.Builder> 
         getProxiesBuilderList() {
      return getProxiesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        com.duox.dtunnel.grpc.pb.Proxy, com.duox.dtunnel.grpc.pb.Proxy.Builder, com.duox.dtunnel.grpc.pb.ProxyOrBuilder> 
        getProxiesFieldBuilder() {
      if (proxiesBuilder_ == null) {
        proxiesBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            com.duox.dtunnel.grpc.pb.Proxy, com.duox.dtunnel.grpc.pb.Proxy.Builder, com.duox.dtunnel.grpc.pb.ProxyOrBuilder>(
                proxies_,
                ((bitField0_ & 0x00000002) != 0),
                getParentForChildren(),
                isClean());
        proxies_ = null;
      }
      return proxiesBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:duox.agent.v1.ConfigPush)
  }

  // @@protoc_insertion_point(class_scope:duox.agent.v1.ConfigPush)
  private static final com.duox.dtunnel.grpc.pb.ConfigPush DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.duox.dtunnel.grpc.pb.ConfigPush();
  }

  public static com.duox.dtunnel.grpc.pb.ConfigPush getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ConfigPush>
      PARSER = new com.google.protobuf.AbstractParser<ConfigPush>() {
    @java.lang.Override
    public ConfigPush parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ConfigPush> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ConfigPush> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.duox.dtunnel.grpc.pb.ConfigPush getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

