// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: duox/agent/v1/agent.proto
// Protobuf Java Version: 4.27.2

package com.duox.dtunnel.grpc.pb;

public interface HeartbeatOrBuilder extends
    // @@protoc_insertion_point(interface_extends:duox.agent.v1.Heartbeat)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 applied_version = 1;</code>
   * @return The appliedVersion.
   */
  int getAppliedVersion();

  /**
   * <code>string agent_version = 2;</code>
   * @return The agentVersion.
   */
  java.lang.String getAgentVersion();
  /**
   * <code>string agent_version = 2;</code>
   * @return The bytes for agentVersion.
   */
  com.google.protobuf.ByteString
      getAgentVersionBytes();

  /**
   * <code>repeated .duox.agent.v1.TunnelReport tunnels = 3;</code>
   */
  java.util.List<com.duox.dtunnel.grpc.pb.TunnelReport> 
      getTunnelsList();
  /**
   * <code>repeated .duox.agent.v1.TunnelReport tunnels = 3;</code>
   */
  com.duox.dtunnel.grpc.pb.TunnelReport getTunnels(int index);
  /**
   * <code>repeated .duox.agent.v1.TunnelReport tunnels = 3;</code>
   */
  int getTunnelsCount();
  /**
   * <code>repeated .duox.agent.v1.TunnelReport tunnels = 3;</code>
   */
  java.util.List<? extends com.duox.dtunnel.grpc.pb.TunnelReportOrBuilder> 
      getTunnelsOrBuilderList();
  /**
   * <code>repeated .duox.agent.v1.TunnelReport tunnels = 3;</code>
   */
  com.duox.dtunnel.grpc.pb.TunnelReportOrBuilder getTunnelsOrBuilder(
      int index);
}
