// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: duox/agent/v1/agent.proto
// Protobuf Java Version: 4.27.2

package com.duox.dtunnel.grpc.pb;

/**
 * Protobuf type {@code duox.agent.v1.Heartbeat}
 */
public final class Heartbeat extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:duox.agent.v1.Heartbeat)
    HeartbeatOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 27,
      /* patch= */ 2,
      /* suffix= */ "",
      Heartbeat.class.getName());
  }
  // Use Heartbeat.newBuilder() to construct.
  private Heartbeat(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private Heartbeat() {
    agentVersion_ = "";
    tunnels_ = java.util.Collections.emptyList();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.duox.dtunnel.grpc.pb.AgentProto.internal_static_duox_agent_v1_Heartbeat_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.duox.dtunnel.grpc.pb.AgentProto.internal_static_duox_agent_v1_Heartbeat_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.duox.dtunnel.grpc.pb.Heartbeat.class, com.duox.dtunnel.grpc.pb.Heartbeat.Builder.class);
  }

  public static final int APPLIED_VERSION_FIELD_NUMBER = 1;
  private int appliedVersion_ = 0;
  /**
   * <code>int32 applied_version = 1;</code>
   * @return The appliedVersion.
   */
  @java.lang.Override
  public int getAppliedVersion() {
    return appliedVersion_;
  }

  public static final int AGENT_VERSION_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object agentVersion_ = "";
  /**
   * <code>string agent_version = 2;</code>
   * @return The agentVersion.
   */
  @java.lang.Override
  public java.lang.String getAgentVersion() {
    java.lang.Object ref = agentVersion_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      agentVersion_ = s;
      return s;
    }
  }
  /**
   * <code>string agent_version = 2;</code>
   * @return The bytes for agentVersion.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getAgentVersionBytes() {
    java.lang.Object ref = agentVersion_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      agentVersion_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TUNNELS_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private java.util.List<com.duox.dtunnel.grpc.pb.TunnelReport> tunnels_;
  /**
   * <code>repeated .duox.agent.v1.TunnelReport tunnels = 3;</code>
   */
  @java.lang.Override
  public java.util.List<com.duox.dtunnel.grpc.pb.TunnelReport> getTunnelsList() {
    return tunnels_;
  }
  /**
   * <code>repeated .duox.agent.v1.TunnelReport tunnels = 3;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.duox.dtunnel.grpc.pb.TunnelReportOrBuilder> 
      getTunnelsOrBuilderList() {
    return tunnels_;
  }
  /**
   * <code>repeated .duox.agent.v1.TunnelReport tunnels = 3;</code>
   */
  @java.lang.Override
  public int getTunnelsCount() {
    return tunnels_.size();
  }
  /**
   * <code>repeated .duox.agent.v1.TunnelReport tunnels = 3;</code>
   */
  @java.lang.Override
  public com.duox.dtunnel.grpc.pb.TunnelReport getTunnels(int index) {
    return tunnels_.get(index);
  }
  /**
   * <code>repeated .duox.agent.v1.TunnelReport tunnels = 3;</code>
   */
  @java.lang.Override
  public com.duox.dtunnel.grpc.pb.TunnelReportOrBuilder getTunnelsOrBuilder(
      int index) {
    return tunnels_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (appliedVersion_ != 0) {
      output.writeInt32(1, appliedVersion_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(agentVersion_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, agentVersion_);
    }
    for (int i = 0; i < tunnels_.size(); i++) {
      output.writeMessage(3, tunnels_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (appliedVersion_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, appliedVersion_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(agentVersion_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, agentVersion_);
    }
    for (int i = 0; i < tunnels_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, tunnels_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.duox.dtunnel.grpc.pb.Heartbeat)) {
      return super.equals(obj);
    }
    com.duox.dtunnel.grpc.pb.Heartbeat other = (com.duox.dtunnel.grpc.pb.Heartbeat) obj;

    if (getAppliedVersion()
        != other.getAppliedVersion()) return false;
    if (!getAgentVersion()
        .equals(other.getAgentVersion())) return false;
    if (!getTunnelsList()
        .equals(other.getTunnelsList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + APPLIED_VERSION_FIELD_NUMBER;
    hash = (53 * hash) + getAppliedVersion();
    hash = (37 * hash) + AGENT_VERSION_FIELD_NUMBER;
    hash = (53 * hash) + getAgentVersion().hashCode();
    if (getTunnelsCount() > 0) {
      hash = (37 * hash) + TUNNELS_FIELD_NUMBER;
      hash = (53 * hash) + getTunnelsList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.duox.dtunnel.grpc.pb.Heartbeat parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.duox.dtunnel.grpc.pb.Heartbeat parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.duox.dtunnel.grpc.pb.Heartbeat parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.duox.dtunnel.grpc.pb.Heartbeat parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.duox.dtunnel.grpc.pb.Heartbeat parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.duox.dtunnel.grpc.pb.Heartbeat parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.duox.dtunnel.grpc.pb.Heartbeat parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.duox.dtunnel.grpc.pb.Heartbeat parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.duox.dtunnel.grpc.pb.Heartbeat parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.duox.dtunnel.grpc.pb.Heartbeat parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.duox.dtunnel.grpc.pb.Heartbeat parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.duox.dtunnel.grpc.pb.Heartbeat parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.duox.dtunnel.grpc.pb.Heartbeat prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code duox.agent.v1.Heartbeat}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:duox.agent.v1.Heartbeat)
      com.duox.dtunnel.grpc.pb.HeartbeatOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.duox.dtunnel.grpc.pb.AgentProto.internal_static_duox_agent_v1_Heartbeat_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.duox.dtunnel.grpc.pb.AgentProto.internal_static_duox_agent_v1_Heartbeat_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.duox.dtunnel.grpc.pb.Heartbeat.class, com.duox.dtunnel.grpc.pb.Heartbeat.Builder.class);
    }

    // Construct using com.duox.dtunnel.grpc.pb.Heartbeat.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      appliedVersion_ = 0;
      agentVersion_ = "";
      if (tunnelsBuilder_ == null) {
        tunnels_ = java.util.Collections.emptyList();
      } else {
        tunnels_ = null;
        tunnelsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000004);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.duox.dtunnel.grpc.pb.AgentProto.internal_static_duox_agent_v1_Heartbeat_descriptor;
    }

    @java.lang.Override
    public com.duox.dtunnel.grpc.pb.Heartbeat getDefaultInstanceForType() {
      return com.duox.dtunnel.grpc.pb.Heartbeat.getDefaultInstance();
    }

    @java.lang.Override
    public com.duox.dtunnel.grpc.pb.Heartbeat build() {
      com.duox.dtunnel.grpc.pb.Heartbeat result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.duox.dtunnel.grpc.pb.Heartbeat buildPartial() {
      com.duox.dtunnel.grpc.pb.Heartbeat result = new com.duox.dtunnel.grpc.pb.Heartbeat(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(com.duox.dtunnel.grpc.pb.Heartbeat result) {
      if (tunnelsBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0)) {
          tunnels_ = java.util.Collections.unmodifiableList(tunnels_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.tunnels_ = tunnels_;
      } else {
        result.tunnels_ = tunnelsBuilder_.build();
      }
    }

    private void buildPartial0(com.duox.dtunnel.grpc.pb.Heartbeat result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.appliedVersion_ = appliedVersion_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.agentVersion_ = agentVersion_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.duox.dtunnel.grpc.pb.Heartbeat) {
        return mergeFrom((com.duox.dtunnel.grpc.pb.Heartbeat)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.duox.dtunnel.grpc.pb.Heartbeat other) {
      if (other == com.duox.dtunnel.grpc.pb.Heartbeat.getDefaultInstance()) return this;
      if (other.getAppliedVersion() != 0) {
        setAppliedVersion(other.getAppliedVersion());
      }
      if (!other.getAgentVersion().isEmpty()) {
        agentVersion_ = other.agentVersion_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (tunnelsBuilder_ == null) {
        if (!other.tunnels_.isEmpty()) {
          if (tunnels_.isEmpty()) {
            tunnels_ = other.tunnels_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureTunnelsIsMutable();
            tunnels_.addAll(other.tunnels_);
          }
          onChanged();
        }
      } else {
        if (!other.tunnels_.isEmpty()) {
          if (tunnelsBuilder_.isEmpty()) {
            tunnelsBuilder_.dispose();
            tunnelsBuilder_ = null;
            tunnels_ = other.tunnels_;
            bitField0_ = (bitField0_ & ~0x00000004);
            tunnelsBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 getTunnelsFieldBuilder() : null;
          } else {
            tunnelsBuilder_.addAllMessages(other.tunnels_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              appliedVersion_ = input.readInt32();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 18: {
              agentVersion_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              com.duox.dtunnel.grpc.pb.TunnelReport m =
                  input.readMessage(
                      com.duox.dtunnel.grpc.pb.TunnelReport.parser(),
                      extensionRegistry);
              if (tunnelsBuilder_ == null) {
                ensureTunnelsIsMutable();
                tunnels_.add(m);
              } else {
                tunnelsBuilder_.addMessage(m);
              }
              break;
            } // case 26
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int appliedVersion_ ;
    /**
     * <code>int32 applied_version = 1;</code>
     * @return The appliedVersion.
     */
    @java.lang.Override
    public int getAppliedVersion() {
      return appliedVersion_;
    }
    /**
     * <code>int32 applied_version = 1;</code>
     * @param value The appliedVersion to set.
     * @return This builder for chaining.
     */
    public Builder setAppliedVersion(int value) {

      appliedVersion_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>int32 applied_version = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearAppliedVersion() {
      bitField0_ = (bitField0_ & ~0x00000001);
      appliedVersion_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object agentVersion_ = "";
    /**
     * <code>string agent_version = 2;</code>
     * @return The agentVersion.
     */
    public java.lang.String getAgentVersion() {
      java.lang.Object ref = agentVersion_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        agentVersion_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string agent_version = 2;</code>
     * @return The bytes for agentVersion.
     */
    public com.google.protobuf.ByteString
        getAgentVersionBytes() {
      java.lang.Object ref = agentVersion_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        agentVersion_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string agent_version = 2;</code>
     * @param value The agentVersion to set.
     * @return This builder for chaining.
     */
    public Builder setAgentVersion(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      agentVersion_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string agent_version = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearAgentVersion() {
      agentVersion_ = getDefaultInstance().getAgentVersion();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string agent_version = 2;</code>
     * @param value The bytes for agentVersion to set.
     * @return This builder for chaining.
     */
    public Builder setAgentVersionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      agentVersion_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private java.util.List<com.duox.dtunnel.grpc.pb.TunnelReport> tunnels_ =
      java.util.Collections.emptyList();
    private void ensureTunnelsIsMutable() {
      if (!((bitField0_ & 0x00000004) != 0)) {
        tunnels_ = new java.util.ArrayList<com.duox.dtunnel.grpc.pb.TunnelReport>(tunnels_);
        bitField0_ |= 0x00000004;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        com.duox.dtunnel.grpc.pb.TunnelReport, com.duox.dtunnel.grpc.pb.TunnelReport.Builder, com.duox.dtunnel.grpc.pb.TunnelReportOrBuilder> tunnelsBuilder_;

    /**
     * <code>repeated .duox.agent.v1.TunnelReport tunnels = 3;</code>
     */
    public java.util.List<com.duox.dtunnel.grpc.pb.TunnelReport> getTunnelsList() {
      if (tunnelsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(tunnels_);
      } else {
        return tunnelsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .duox.agent.v1.TunnelReport tunnels = 3;</code>
     */
    public int getTunnelsCount() {
      if (tunnelsBuilder_ == null) {
        return tunnels_.size();
      } else {
        return tunnelsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .duox.agent.v1.TunnelReport tunnels = 3;</code>
     */
    public com.duox.dtunnel.grpc.pb.TunnelReport getTunnels(int index) {
      if (tunnelsBuilder_ == null) {
        return tunnels_.get(index);
      } else {
        return tunnelsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .duox.agent.v1.TunnelReport tunnels = 3;</code>
     */
    public Builder setTunnels(
        int index, com.duox.dtunnel.grpc.pb.TunnelReport value) {
      if (tunnelsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTunnelsIsMutable();
        tunnels_.set(index, value);
        onChanged();
      } else {
        tunnelsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .duox.agent.v1.TunnelReport tunnels = 3;</code>
     */
    public Builder setTunnels(
        int index, com.duox.dtunnel.grpc.pb.TunnelReport.Builder builderForValue) {
      if (tunnelsBuilder_ == null) {
        ensureTunnelsIsMutable();
        tunnels_.set(index, builderForValue.build());
        onChanged();
      } else {
        tunnelsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .duox.agent.v1.TunnelReport tunnels = 3;</code>
     */
    public Builder addTunnels(com.duox.dtunnel.grpc.pb.TunnelReport value) {
      if (tunnelsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTunnelsIsMutable();
        tunnels_.add(value);
        onChanged();
      } else {
        tunnelsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .duox.agent.v1.TunnelReport tunnels = 3;</code>
     */
    public Builder addTunnels(
        int index, com.duox.dtunnel.grpc.pb.TunnelReport value) {
      if (tunnelsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTunnelsIsMutable();
        tunnels_.add(index, value);
        onChanged();
      } else {
        tunnelsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .duox.agent.v1.TunnelReport tunnels = 3;</code>
     */
    public Builder addTunnels(
        com.duox.dtunnel.grpc.pb.TunnelReport.Builder builderForValue) {
      if (tunnelsBuilder_ == null) {
        ensureTunnelsIsMutable();
        tunnels_.add(builderForValue.build());
        onChanged();
      } else {
        tunnelsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .duox.agent.v1.TunnelReport tunnels = 3;</code>
     */
    public Builder addTunnels(
        int index, com.duox.dtunnel.grpc.pb.TunnelReport.Builder builderForValue) {
      if (tunnelsBuilder_ == null) {
        ensureTunnelsIsMutable();
        tunnels_.add(index, builderForValue.build());
        onChanged();
      } else {
        tunnelsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .duox.agent.v1.TunnelReport tunnels = 3;</code>
     */
    public Builder addAllTunnels(
        java.lang.Iterable<? extends com.duox.dtunnel.grpc.pb.TunnelReport> values) {
      if (tunnelsBuilder_ == null) {
        ensureTunnelsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, tunnels_);
        onChanged();
      } else {
        tunnelsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .duox.agent.v1.TunnelReport tunnels = 3;</code>
     */
    public Builder clearTunnels() {
      if (tunnelsBuilder_ == null) {
        tunnels_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
      } else {
        tunnelsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .duox.agent.v1.TunnelReport tunnels = 3;</code>
     */
    public Builder removeTunnels(int index) {
      if (tunnelsBuilder_ == null) {
        ensureTunnelsIsMutable();
        tunnels_.remove(index);
        onChanged();
      } else {
        tunnelsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .duox.agent.v1.TunnelReport tunnels = 3;</code>
     */
    public com.duox.dtunnel.grpc.pb.TunnelReport.Builder getTunnelsBuilder(
        int index) {
      return getTunnelsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .duox.agent.v1.TunnelReport tunnels = 3;</code>
     */
    public com.duox.dtunnel.grpc.pb.TunnelReportOrBuilder getTunnelsOrBuilder(
        int index) {
      if (tunnelsBuilder_ == null) {
        return tunnels_.get(index);  } else {
        return tunnelsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .duox.agent.v1.TunnelReport tunnels = 3;</code>
     */
    public java.util.List<? extends com.duox.dtunnel.grpc.pb.TunnelReportOrBuilder> 
         getTunnelsOrBuilderList() {
      if (tunnelsBuilder_ != null) {
        return tunnelsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(tunnels_);
      }
    }
    /**
     * <code>repeated .duox.agent.v1.TunnelReport tunnels = 3;</code>
     */
    public com.duox.dtunnel.grpc.pb.TunnelReport.Builder addTunnelsBuilder() {
      return getTunnelsFieldBuilder().addBuilder(
          com.duox.dtunnel.grpc.pb.TunnelReport.getDefaultInstance());
    }
    /**
     * <code>repeated .duox.agent.v1.TunnelReport tunnels = 3;</code>
     */
    public com.duox.dtunnel.grpc.pb.TunnelReport.Builder addTunnelsBuilder(
        int index) {
      return getTunnelsFieldBuilder().addBuilder(
          index, com.duox.dtunnel.grpc.pb.TunnelReport.getDefaultInstance());
    }
    /**
     * <code>repeated .duox.agent.v1.TunnelReport tunnels = 3;</code>
     */
    public java.util.List<com.duox.dtunnel.grpc.pb.TunnelReport.Builder> 
         getTunnelsBuilderList() {
      return getTunnelsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        com.duox.dtunnel.grpc.pb.TunnelReport, com.duox.dtunnel.grpc.pb.TunnelReport.Builder, com.duox.dtunnel.grpc.pb.TunnelReportOrBuilder> 
        getTunnelsFieldBuilder() {
      if (tunnelsBuilder_ == null) {
        tunnelsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            com.duox.dtunnel.grpc.pb.TunnelReport, com.duox.dtunnel.grpc.pb.TunnelReport.Builder, com.duox.dtunnel.grpc.pb.TunnelReportOrBuilder>(
                tunnels_,
                ((bitField0_ & 0x00000004) != 0),
                getParentForChildren(),
                isClean());
        tunnels_ = null;
      }
      return tunnelsBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:duox.agent.v1.Heartbeat)
  }

  // @@protoc_insertion_point(class_scope:duox.agent.v1.Heartbeat)
  private static final com.duox.dtunnel.grpc.pb.Heartbeat DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.duox.dtunnel.grpc.pb.Heartbeat();
  }

  public static com.duox.dtunnel.grpc.pb.Heartbeat getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Heartbeat>
      PARSER = new com.google.protobuf.AbstractParser<Heartbeat>() {
    @java.lang.Override
    public Heartbeat parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Heartbeat> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Heartbeat> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.duox.dtunnel.grpc.pb.Heartbeat getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

