// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: duox/agent/v1/agent.proto
// Protobuf Java Version: 4.27.2

package com.duox.dtunnel.grpc.pb;

public interface HeartbeatAckOrBuilder extends
    // @@protoc_insertion_point(interface_extends:duox.agent.v1.HeartbeatAck)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 desired_version = 1;</code>
   * @return The desiredVersion.
   */
  int getDesiredVersion();
}
