// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: duox/agent/v1/agent.proto
// Protobuf Java Version: 4.27.2

package com.duox.dtunnel.grpc.pb;

public interface HelloOrBuilder extends
    // @@protoc_insertion_point(interface_extends:duox.agent.v1.Hello)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string token = 1;</code>
   * @return The token.
   */
  java.lang.String getToken();
  /**
   * <code>string token = 1;</code>
   * @return The bytes for token.
   */
  com.google.protobuf.ByteString
      getTokenBytes();

  /**
   * <code>string agent_version = 2;</code>
   * @return The agentVersion.
   */
  java.lang.String getAgentVersion();
  /**
   * <code>string agent_version = 2;</code>
   * @return The bytes for agentVersion.
   */
  com.google.protobuf.ByteString
      getAgentVersionBytes();

  /**
   * <code>int32 applied_version = 3;</code>
   * @return The appliedVersion.
   */
  int getAppliedVersion();
}
