// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: duox/agent/v1/agent.proto
// Protobuf Java Version: 4.27.2

package com.duox.dtunnel.grpc.pb;

/**
 * Protobuf type {@code duox.agent.v1.Proxy}
 */
public final class Proxy extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:duox.agent.v1.Proxy)
    ProxyOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 27,
      /* patch= */ 2,
      /* suffix= */ "",
      Proxy.class.getName());
  }
  // Use Proxy.newBuilder() to construct.
  private Proxy(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private Proxy() {
    tunnelId_ = "";
    name_ = "";
    type_ = "";
    serverAddr_ = "";
    domain_ = "";
    localHost_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.duox.dtunnel.grpc.pb.AgentProto.internal_static_duox_agent_v1_Proxy_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.duox.dtunnel.grpc.pb.AgentProto.internal_static_duox_agent_v1_Proxy_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.duox.dtunnel.grpc.pb.Proxy.class, com.duox.dtunnel.grpc.pb.Proxy.Builder.class);
  }

  public static final int TUNNEL_ID_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object tunnelId_ = "";
  /**
   * <code>string tunnel_id = 1;</code>
   * @return The tunnelId.
   */
  @java.lang.Override
  public java.lang.String getTunnelId() {
    java.lang.Object ref = tunnelId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      tunnelId_ = s;
      return s;
    }
  }
  /**
   * <code>string tunnel_id = 1;</code>
   * @return The bytes for tunnelId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTunnelIdBytes() {
    java.lang.Object ref = tunnelId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      tunnelId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int NAME_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object name_ = "";
  /**
   * <code>string name = 2;</code>
   * @return The name.
   */
  @java.lang.Override
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <code>string name = 2;</code>
   * @return The bytes for name.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TYPE_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object type_ = "";
  /**
   * <pre>
   * tcp | udp | http
   * </pre>
   *
   * <code>string type = 3;</code>
   * @return The type.
   */
  @java.lang.Override
  public java.lang.String getType() {
    java.lang.Object ref = type_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      type_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * tcp | udp | http
   * </pre>
   *
   * <code>string type = 3;</code>
   * @return The bytes for type.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTypeBytes() {
    java.lang.Object ref = type_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      type_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SERVER_ADDR_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private volatile java.lang.Object serverAddr_ = "";
  /**
   * <code>string server_addr = 4;</code>
   * @return The serverAddr.
   */
  @java.lang.Override
  public java.lang.String getServerAddr() {
    java.lang.Object ref = serverAddr_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      serverAddr_ = s;
      return s;
    }
  }
  /**
   * <code>string server_addr = 4;</code>
   * @return The bytes for serverAddr.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getServerAddrBytes() {
    java.lang.Object ref = serverAddr_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      serverAddr_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SERVER_PORT_FIELD_NUMBER = 5;
  private int serverPort_ = 0;
  /**
   * <code>int32 server_port = 5;</code>
   * @return The serverPort.
   */
  @java.lang.Override
  public int getServerPort() {
    return serverPort_;
  }

  public static final int REMOTE_PORT_FIELD_NUMBER = 6;
  private int remotePort_ = 0;
  /**
   * <code>int32 remote_port = 6;</code>
   * @return The remotePort.
   */
  @java.lang.Override
  public int getRemotePort() {
    return remotePort_;
  }

  public static final int DOMAIN_FIELD_NUMBER = 7;
  @SuppressWarnings("serial")
  private volatile java.lang.Object domain_ = "";
  /**
   * <pre>
   * http only (detail.md §3.6)
   * </pre>
   *
   * <code>string domain = 7;</code>
   * @return The domain.
   */
  @java.lang.Override
  public java.lang.String getDomain() {
    java.lang.Object ref = domain_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      domain_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * http only (detail.md §3.6)
   * </pre>
   *
   * <code>string domain = 7;</code>
   * @return The bytes for domain.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDomainBytes() {
    java.lang.Object ref = domain_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      domain_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int LOCAL_HOST_FIELD_NUMBER = 8;
  @SuppressWarnings("serial")
  private volatile java.lang.Object localHost_ = "";
  /**
   * <code>string local_host = 8;</code>
   * @return The localHost.
   */
  @java.lang.Override
  public java.lang.String getLocalHost() {
    java.lang.Object ref = localHost_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      localHost_ = s;
      return s;
    }
  }
  /**
   * <code>string local_host = 8;</code>
   * @return The bytes for localHost.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getLocalHostBytes() {
    java.lang.Object ref = localHost_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      localHost_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int LOCAL_PORT_FIELD_NUMBER = 9;
  private int localPort_ = 0;
  /**
   * <code>int32 local_port = 9;</code>
   * @return The localPort.
   */
  @java.lang.Override
  public int getLocalPort() {
    return localPort_;
  }

  public static final int BANDWIDTH_LIMIT_MBPS_FIELD_NUMBER = 10;
  private int bandwidthLimitMbps_ = 0;
  /**
   * <code>int32 bandwidth_limit_mbps = 10;</code>
   * @return The bandwidthLimitMbps.
   */
  @java.lang.Override
  public int getBandwidthLimitMbps() {
    return bandwidthLimitMbps_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(tunnelId_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, tunnelId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(name_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, name_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(type_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 3, type_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(serverAddr_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 4, serverAddr_);
    }
    if (serverPort_ != 0) {
      output.writeInt32(5, serverPort_);
    }
    if (remotePort_ != 0) {
      output.writeInt32(6, remotePort_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(domain_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 7, domain_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(localHost_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 8, localHost_);
    }
    if (localPort_ != 0) {
      output.writeInt32(9, localPort_);
    }
    if (bandwidthLimitMbps_ != 0) {
      output.writeInt32(10, bandwidthLimitMbps_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(tunnelId_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, tunnelId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(name_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, name_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(type_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(3, type_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(serverAddr_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(4, serverAddr_);
    }
    if (serverPort_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(5, serverPort_);
    }
    if (remotePort_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(6, remotePort_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(domain_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(7, domain_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(localHost_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(8, localHost_);
    }
    if (localPort_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(9, localPort_);
    }
    if (bandwidthLimitMbps_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(10, bandwidthLimitMbps_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.duox.dtunnel.grpc.pb.Proxy)) {
      return super.equals(obj);
    }
    com.duox.dtunnel.grpc.pb.Proxy other = (com.duox.dtunnel.grpc.pb.Proxy) obj;

    if (!getTunnelId()
        .equals(other.getTunnelId())) return false;
    if (!getName()
        .equals(other.getName())) return false;
    if (!getType()
        .equals(other.getType())) return false;
    if (!getServerAddr()
        .equals(other.getServerAddr())) return false;
    if (getServerPort()
        != other.getServerPort()) return false;
    if (getRemotePort()
        != other.getRemotePort()) return false;
    if (!getDomain()
        .equals(other.getDomain())) return false;
    if (!getLocalHost()
        .equals(other.getLocalHost())) return false;
    if (getLocalPort()
        != other.getLocalPort()) return false;
    if (getBandwidthLimitMbps()
        != other.getBandwidthLimitMbps()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TUNNEL_ID_FIELD_NUMBER;
    hash = (53 * hash) + getTunnelId().hashCode();
    hash = (37 * hash) + NAME_FIELD_NUMBER;
    hash = (53 * hash) + getName().hashCode();
    hash = (37 * hash) + TYPE_FIELD_NUMBER;
    hash = (53 * hash) + getType().hashCode();
    hash = (37 * hash) + SERVER_ADDR_FIELD_NUMBER;
    hash = (53 * hash) + getServerAddr().hashCode();
    hash = (37 * hash) + SERVER_PORT_FIELD_NUMBER;
    hash = (53 * hash) + getServerPort();
    hash = (37 * hash) + REMOTE_PORT_FIELD_NUMBER;
    hash = (53 * hash) + getRemotePort();
    hash = (37 * hash) + DOMAIN_FIELD_NUMBER;
    hash = (53 * hash) + getDomain().hashCode();
    hash = (37 * hash) + LOCAL_HOST_FIELD_NUMBER;
    hash = (53 * hash) + getLocalHost().hashCode();
    hash = (37 * hash) + LOCAL_PORT_FIELD_NUMBER;
    hash = (53 * hash) + getLocalPort();
    hash = (37 * hash) + BANDWIDTH_LIMIT_MBPS_FIELD_NUMBER;
    hash = (53 * hash) + getBandwidthLimitMbps();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.duox.dtunnel.grpc.pb.Proxy parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.duox.dtunnel.grpc.pb.Proxy parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.duox.dtunnel.grpc.pb.Proxy parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.duox.dtunnel.grpc.pb.Proxy parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.duox.dtunnel.grpc.pb.Proxy parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.duox.dtunnel.grpc.pb.Proxy parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.duox.dtunnel.grpc.pb.Proxy parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.duox.dtunnel.grpc.pb.Proxy parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.duox.dtunnel.grpc.pb.Proxy parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.duox.dtunnel.grpc.pb.Proxy parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.duox.dtunnel.grpc.pb.Proxy parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.duox.dtunnel.grpc.pb.Proxy parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.duox.dtunnel.grpc.pb.Proxy prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code duox.agent.v1.Proxy}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:duox.agent.v1.Proxy)
      com.duox.dtunnel.grpc.pb.ProxyOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.duox.dtunnel.grpc.pb.AgentProto.internal_static_duox_agent_v1_Proxy_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.duox.dtunnel.grpc.pb.AgentProto.internal_static_duox_agent_v1_Proxy_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.duox.dtunnel.grpc.pb.Proxy.class, com.duox.dtunnel.grpc.pb.Proxy.Builder.class);
    }

    // Construct using com.duox.dtunnel.grpc.pb.Proxy.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      tunnelId_ = "";
      name_ = "";
      type_ = "";
      serverAddr_ = "";
      serverPort_ = 0;
      remotePort_ = 0;
      domain_ = "";
      localHost_ = "";
      localPort_ = 0;
      bandwidthLimitMbps_ = 0;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.duox.dtunnel.grpc.pb.AgentProto.internal_static_duox_agent_v1_Proxy_descriptor;
    }

    @java.lang.Override
    public com.duox.dtunnel.grpc.pb.Proxy getDefaultInstanceForType() {
      return com.duox.dtunnel.grpc.pb.Proxy.getDefaultInstance();
    }

    @java.lang.Override
    public com.duox.dtunnel.grpc.pb.Proxy build() {
      com.duox.dtunnel.grpc.pb.Proxy result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.duox.dtunnel.grpc.pb.Proxy buildPartial() {
      com.duox.dtunnel.grpc.pb.Proxy result = new com.duox.dtunnel.grpc.pb.Proxy(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.duox.dtunnel.grpc.pb.Proxy result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.tunnelId_ = tunnelId_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.name_ = name_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.type_ = type_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.serverAddr_ = serverAddr_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.serverPort_ = serverPort_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.remotePort_ = remotePort_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.domain_ = domain_;
      }
      if (((from_bitField0_ & 0x00000080) != 0)) {
        result.localHost_ = localHost_;
      }
      if (((from_bitField0_ & 0x00000100) != 0)) {
        result.localPort_ = localPort_;
      }
      if (((from_bitField0_ & 0x00000200) != 0)) {
        result.bandwidthLimitMbps_ = bandwidthLimitMbps_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.duox.dtunnel.grpc.pb.Proxy) {
        return mergeFrom((com.duox.dtunnel.grpc.pb.Proxy)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.duox.dtunnel.grpc.pb.Proxy other) {
      if (other == com.duox.dtunnel.grpc.pb.Proxy.getDefaultInstance()) return this;
      if (!other.getTunnelId().isEmpty()) {
        tunnelId_ = other.tunnelId_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getName().isEmpty()) {
        name_ = other.name_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (!other.getType().isEmpty()) {
        type_ = other.type_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (!other.getServerAddr().isEmpty()) {
        serverAddr_ = other.serverAddr_;
        bitField0_ |= 0x00000008;
        onChanged();
      }
      if (other.getServerPort() != 0) {
        setServerPort(other.getServerPort());
      }
      if (other.getRemotePort() != 0) {
        setRemotePort(other.getRemotePort());
      }
      if (!other.getDomain().isEmpty()) {
        domain_ = other.domain_;
        bitField0_ |= 0x00000040;
        onChanged();
      }
      if (!other.getLocalHost().isEmpty()) {
        localHost_ = other.localHost_;
        bitField0_ |= 0x00000080;
        onChanged();
      }
      if (other.getLocalPort() != 0) {
        setLocalPort(other.getLocalPort());
      }
      if (other.getBandwidthLimitMbps() != 0) {
        setBandwidthLimitMbps(other.getBandwidthLimitMbps());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              tunnelId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              name_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              type_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              serverAddr_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 40: {
              serverPort_ = input.readInt32();
              bitField0_ |= 0x00000010;
              break;
            } // case 40
            case 48: {
              remotePort_ = input.readInt32();
              bitField0_ |= 0x00000020;
              break;
            } // case 48
            case 58: {
              domain_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000040;
              break;
            } // case 58
            case 66: {
              localHost_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000080;
              break;
            } // case 66
            case 72: {
              localPort_ = input.readInt32();
              bitField0_ |= 0x00000100;
              break;
            } // case 72
            case 80: {
              bandwidthLimitMbps_ = input.readInt32();
              bitField0_ |= 0x00000200;
              break;
            } // case 80
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object tunnelId_ = "";
    /**
     * <code>string tunnel_id = 1;</code>
     * @return The tunnelId.
     */
    public java.lang.String getTunnelId() {
      java.lang.Object ref = tunnelId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        tunnelId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string tunnel_id = 1;</code>
     * @return The bytes for tunnelId.
     */
    public com.google.protobuf.ByteString
        getTunnelIdBytes() {
      java.lang.Object ref = tunnelId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        tunnelId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string tunnel_id = 1;</code>
     * @param value The tunnelId to set.
     * @return This builder for chaining.
     */
    public Builder setTunnelId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      tunnelId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string tunnel_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearTunnelId() {
      tunnelId_ = getDefaultInstance().getTunnelId();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string tunnel_id = 1;</code>
     * @param value The bytes for tunnelId to set.
     * @return This builder for chaining.
     */
    public Builder setTunnelIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      tunnelId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object name_ = "";
    /**
     * <code>string name = 2;</code>
     * @return The name.
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string name = 2;</code>
     * @param value The name to set.
     * @return This builder for chaining.
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      name_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string name = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearName() {
      name_ = getDefaultInstance().getName();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string name = 2;</code>
     * @param value The bytes for name to set.
     * @return This builder for chaining.
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      name_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private java.lang.Object type_ = "";
    /**
     * <pre>
     * tcp | udp | http
     * </pre>
     *
     * <code>string type = 3;</code>
     * @return The type.
     */
    public java.lang.String getType() {
      java.lang.Object ref = type_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        type_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * tcp | udp | http
     * </pre>
     *
     * <code>string type = 3;</code>
     * @return The bytes for type.
     */
    public com.google.protobuf.ByteString
        getTypeBytes() {
      java.lang.Object ref = type_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        type_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * tcp | udp | http
     * </pre>
     *
     * <code>string type = 3;</code>
     * @param value The type to set.
     * @return This builder for chaining.
     */
    public Builder setType(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      type_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * tcp | udp | http
     * </pre>
     *
     * <code>string type = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearType() {
      type_ = getDefaultInstance().getType();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * tcp | udp | http
     * </pre>
     *
     * <code>string type = 3;</code>
     * @param value The bytes for type to set.
     * @return This builder for chaining.
     */
    public Builder setTypeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      type_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private java.lang.Object serverAddr_ = "";
    /**
     * <code>string server_addr = 4;</code>
     * @return The serverAddr.
     */
    public java.lang.String getServerAddr() {
      java.lang.Object ref = serverAddr_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        serverAddr_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string server_addr = 4;</code>
     * @return The bytes for serverAddr.
     */
    public com.google.protobuf.ByteString
        getServerAddrBytes() {
      java.lang.Object ref = serverAddr_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        serverAddr_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string server_addr = 4;</code>
     * @param value The serverAddr to set.
     * @return This builder for chaining.
     */
    public Builder setServerAddr(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      serverAddr_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>string server_addr = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearServerAddr() {
      serverAddr_ = getDefaultInstance().getServerAddr();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     * <code>string server_addr = 4;</code>
     * @param value The bytes for serverAddr to set.
     * @return This builder for chaining.
     */
    public Builder setServerAddrBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      serverAddr_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }

    private int serverPort_ ;
    /**
     * <code>int32 server_port = 5;</code>
     * @return The serverPort.
     */
    @java.lang.Override
    public int getServerPort() {
      return serverPort_;
    }
    /**
     * <code>int32 server_port = 5;</code>
     * @param value The serverPort to set.
     * @return This builder for chaining.
     */
    public Builder setServerPort(int value) {

      serverPort_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>int32 server_port = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearServerPort() {
      bitField0_ = (bitField0_ & ~0x00000010);
      serverPort_ = 0;
      onChanged();
      return this;
    }

    private int remotePort_ ;
    /**
     * <code>int32 remote_port = 6;</code>
     * @return The remotePort.
     */
    @java.lang.Override
    public int getRemotePort() {
      return remotePort_;
    }
    /**
     * <code>int32 remote_port = 6;</code>
     * @param value The remotePort to set.
     * @return This builder for chaining.
     */
    public Builder setRemotePort(int value) {

      remotePort_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>int32 remote_port = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearRemotePort() {
      bitField0_ = (bitField0_ & ~0x00000020);
      remotePort_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object domain_ = "";
    /**
     * <pre>
     * http only (detail.md §3.6)
     * </pre>
     *
     * <code>string domain = 7;</code>
     * @return The domain.
     */
    public java.lang.String getDomain() {
      java.lang.Object ref = domain_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        domain_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * http only (detail.md §3.6)
     * </pre>
     *
     * <code>string domain = 7;</code>
     * @return The bytes for domain.
     */
    public com.google.protobuf.ByteString
        getDomainBytes() {
      java.lang.Object ref = domain_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        domain_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * http only (detail.md §3.6)
     * </pre>
     *
     * <code>string domain = 7;</code>
     * @param value The domain to set.
     * @return This builder for chaining.
     */
    public Builder setDomain(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      domain_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * http only (detail.md §3.6)
     * </pre>
     *
     * <code>string domain = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearDomain() {
      domain_ = getDefaultInstance().getDomain();
      bitField0_ = (bitField0_ & ~0x00000040);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * http only (detail.md §3.6)
     * </pre>
     *
     * <code>string domain = 7;</code>
     * @param value The bytes for domain to set.
     * @return This builder for chaining.
     */
    public Builder setDomainBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      domain_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }

    private java.lang.Object localHost_ = "";
    /**
     * <code>string local_host = 8;</code>
     * @return The localHost.
     */
    public java.lang.String getLocalHost() {
      java.lang.Object ref = localHost_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        localHost_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string local_host = 8;</code>
     * @return The bytes for localHost.
     */
    public com.google.protobuf.ByteString
        getLocalHostBytes() {
      java.lang.Object ref = localHost_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        localHost_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string local_host = 8;</code>
     * @param value The localHost to set.
     * @return This builder for chaining.
     */
    public Builder setLocalHost(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      localHost_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <code>string local_host = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearLocalHost() {
      localHost_ = getDefaultInstance().getLocalHost();
      bitField0_ = (bitField0_ & ~0x00000080);
      onChanged();
      return this;
    }
    /**
     * <code>string local_host = 8;</code>
     * @param value The bytes for localHost to set.
     * @return This builder for chaining.
     */
    public Builder setLocalHostBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      localHost_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }

    private int localPort_ ;
    /**
     * <code>int32 local_port = 9;</code>
     * @return The localPort.
     */
    @java.lang.Override
    public int getLocalPort() {
      return localPort_;
    }
    /**
     * <code>int32 local_port = 9;</code>
     * @param value The localPort to set.
     * @return This builder for chaining.
     */
    public Builder setLocalPort(int value) {

      localPort_ = value;
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }
    /**
     * <code>int32 local_port = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearLocalPort() {
      bitField0_ = (bitField0_ & ~0x00000100);
      localPort_ = 0;
      onChanged();
      return this;
    }

    private int bandwidthLimitMbps_ ;
    /**
     * <code>int32 bandwidth_limit_mbps = 10;</code>
     * @return The bandwidthLimitMbps.
     */
    @java.lang.Override
    public int getBandwidthLimitMbps() {
      return bandwidthLimitMbps_;
    }
    /**
     * <code>int32 bandwidth_limit_mbps = 10;</code>
     * @param value The bandwidthLimitMbps to set.
     * @return This builder for chaining.
     */
    public Builder setBandwidthLimitMbps(int value) {

      bandwidthLimitMbps_ = value;
      bitField0_ |= 0x00000200;
      onChanged();
      return this;
    }
    /**
     * <code>int32 bandwidth_limit_mbps = 10;</code>
     * @return This builder for chaining.
     */
    public Builder clearBandwidthLimitMbps() {
      bitField0_ = (bitField0_ & ~0x00000200);
      bandwidthLimitMbps_ = 0;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:duox.agent.v1.Proxy)
  }

  // @@protoc_insertion_point(class_scope:duox.agent.v1.Proxy)
  private static final com.duox.dtunnel.grpc.pb.Proxy DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.duox.dtunnel.grpc.pb.Proxy();
  }

  public static com.duox.dtunnel.grpc.pb.Proxy getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Proxy>
      PARSER = new com.google.protobuf.AbstractParser<Proxy>() {
    @java.lang.Override
    public Proxy parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Proxy> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Proxy> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.duox.dtunnel.grpc.pb.Proxy getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

