// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: duox/agent/v1/agent.proto
// Protobuf Java Version: 4.27.2

package com.duox.dtunnel.grpc.pb;

public interface ProxyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:duox.agent.v1.Proxy)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string tunnel_id = 1;</code>
   * @return The tunnelId.
   */
  java.lang.String getTunnelId();
  /**
   * <code>string tunnel_id = 1;</code>
   * @return The bytes for tunnelId.
   */
  com.google.protobuf.ByteString
      getTunnelIdBytes();

  /**
   * <code>string name = 2;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 2;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <pre>
   * tcp | udp | http
   * </pre>
   *
   * <code>string type = 3;</code>
   * @return The type.
   */
  java.lang.String getType();
  /**
   * <pre>
   * tcp | udp | http
   * </pre>
   *
   * <code>string type = 3;</code>
   * @return The bytes for type.
   */
  com.google.protobuf.ByteString
      getTypeBytes();

  /**
   * <code>string server_addr = 4;</code>
   * @return The serverAddr.
   */
  java.lang.String getServerAddr();
  /**
   * <code>string server_addr = 4;</code>
   * @return The bytes for serverAddr.
   */
  com.google.protobuf.ByteString
      getServerAddrBytes();

  /**
   * <code>int32 server_port = 5;</code>
   * @return The serverPort.
   */
  int getServerPort();

  /**
   * <code>int32 remote_port = 6;</code>
   * @return The remotePort.
   */
  int getRemotePort();

  /**
   * <pre>
   * http only (detail.md §3.6)
   * </pre>
   *
   * <code>string domain = 7;</code>
   * @return The domain.
   */
  java.lang.String getDomain();
  /**
   * <pre>
   * http only (detail.md §3.6)
   * </pre>
   *
   * <code>string domain = 7;</code>
   * @return The bytes for domain.
   */
  com.google.protobuf.ByteString
      getDomainBytes();

  /**
   * <code>string local_host = 8;</code>
   * @return The localHost.
   */
  java.lang.String getLocalHost();
  /**
   * <code>string local_host = 8;</code>
   * @return The bytes for localHost.
   */
  com.google.protobuf.ByteString
      getLocalHostBytes();

  /**
   * <code>int32 local_port = 9;</code>
   * @return The localPort.
   */
  int getLocalPort();

  /**
   * <code>int32 bandwidth_limit_mbps = 10;</code>
   * @return The bandwidthLimitMbps.
   */
  int getBandwidthLimitMbps();
}
