// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: duox/agent/v1/agent.proto
// Protobuf Java Version: 4.27.2

package com.duox.dtunnel.grpc.pb;

public interface RevokedOrBuilder extends
    // @@protoc_insertion_point(interface_extends:duox.agent.v1.Revoked)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string reason = 1;</code>
   * @return The reason.
   */
  java.lang.String getReason();
  /**
   * <code>string reason = 1;</code>
   * @return The bytes for reason.
   */
  com.google.protobuf.ByteString
      getReasonBytes();
}
