// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: duox/agent/v1/agent.proto
// Protobuf Java Version: 4.27.2

package com.duox.dtunnel.grpc.pb;

public interface ServerMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:duox.agent.v1.ServerMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.duox.agent.v1.ConfigPush config = 1;</code>
   * @return Whether the config field is set.
   */
  boolean hasConfig();
  /**
   * <code>.duox.agent.v1.ConfigPush config = 1;</code>
   * @return The config.
   */
  com.duox.dtunnel.grpc.pb.ConfigPush getConfig();
  /**
   * <code>.duox.agent.v1.ConfigPush config = 1;</code>
   */
  com.duox.dtunnel.grpc.pb.ConfigPushOrBuilder getConfigOrBuilder();

  /**
   * <code>.duox.agent.v1.Revoked revoked = 2;</code>
   * @return Whether the revoked field is set.
   */
  boolean hasRevoked();
  /**
   * <code>.duox.agent.v1.Revoked revoked = 2;</code>
   * @return The revoked.
   */
  com.duox.dtunnel.grpc.pb.Revoked getRevoked();
  /**
   * <code>.duox.agent.v1.Revoked revoked = 2;</code>
   */
  com.duox.dtunnel.grpc.pb.RevokedOrBuilder getRevokedOrBuilder();

  /**
   * <code>.duox.agent.v1.HeartbeatAck ack = 3;</code>
   * @return Whether the ack field is set.
   */
  boolean hasAck();
  /**
   * <code>.duox.agent.v1.HeartbeatAck ack = 3;</code>
   * @return The ack.
   */
  com.duox.dtunnel.grpc.pb.HeartbeatAck getAck();
  /**
   * <code>.duox.agent.v1.HeartbeatAck ack = 3;</code>
   */
  com.duox.dtunnel.grpc.pb.HeartbeatAckOrBuilder getAckOrBuilder();

  com.duox.dtunnel.grpc.pb.ServerMessage.KindCase getKindCase();
}
