// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: duox/agent/v1/agent.proto
// Protobuf Java Version: 4.27.2

package com.duox.dtunnel.grpc.pb;

/**
 * <pre>
 * Server -&gt; agent on the Control stream.
 * </pre>
 *
 * Protobuf type {@code duox.agent.v1.ServerMessage}
 */
public final class ServerMessage extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:duox.agent.v1.ServerMessage)
    ServerMessageOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 27,
      /* patch= */ 2,
      /* suffix= */ "",
      ServerMessage.class.getName());
  }
  // Use ServerMessage.newBuilder() to construct.
  private ServerMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private ServerMessage() {
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.duox.dtunnel.grpc.pb.AgentProto.internal_static_duox_agent_v1_ServerMessage_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.duox.dtunnel.grpc.pb.AgentProto.internal_static_duox_agent_v1_ServerMessage_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.duox.dtunnel.grpc.pb.ServerMessage.class, com.duox.dtunnel.grpc.pb.ServerMessage.Builder.class);
  }

  private int kindCase_ = 0;
  @SuppressWarnings("serial")
  private java.lang.Object kind_;
  public enum KindCase
      implements com.google.protobuf.Internal.EnumLite,
          com.google.protobuf.AbstractMessage.InternalOneOfEnum {
    CONFIG(1),
    REVOKED(2),
    ACK(3),
    KIND_NOT_SET(0);
    private final int value;
    private KindCase(int value) {
      this.value = value;
    }
    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static KindCase valueOf(int value) {
      return forNumber(value);
    }

    public static KindCase forNumber(int value) {
      switch (value) {
        case 1: return CONFIG;
        case 2: return REVOKED;
        case 3: return ACK;
        case 0: return KIND_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public KindCase
  getKindCase() {
    return KindCase.forNumber(
        kindCase_);
  }

  public static final int CONFIG_FIELD_NUMBER = 1;
  /**
   * <code>.duox.agent.v1.ConfigPush config = 1;</code>
   * @return Whether the config field is set.
   */
  @java.lang.Override
  public boolean hasConfig() {
    return kindCase_ == 1;
  }
  /**
   * <code>.duox.agent.v1.ConfigPush config = 1;</code>
   * @return The config.
   */
  @java.lang.Override
  public com.duox.dtunnel.grpc.pb.ConfigPush getConfig() {
    if (kindCase_ == 1) {
       return (com.duox.dtunnel.grpc.pb.ConfigPush) kind_;
    }
    return com.duox.dtunnel.grpc.pb.ConfigPush.getDefaultInstance();
  }
  /**
   * <code>.duox.agent.v1.ConfigPush config = 1;</code>
   */
  @java.lang.Override
  public com.duox.dtunnel.grpc.pb.ConfigPushOrBuilder getConfigOrBuilder() {
    if (kindCase_ == 1) {
       return (com.duox.dtunnel.grpc.pb.ConfigPush) kind_;
    }
    return com.duox.dtunnel.grpc.pb.ConfigPush.getDefaultInstance();
  }

  public static final int REVOKED_FIELD_NUMBER = 2;
  /**
   * <code>.duox.agent.v1.Revoked revoked = 2;</code>
   * @return Whether the revoked field is set.
   */
  @java.lang.Override
  public boolean hasRevoked() {
    return kindCase_ == 2;
  }
  /**
   * <code>.duox.agent.v1.Revoked revoked = 2;</code>
   * @return The revoked.
   */
  @java.lang.Override
  public com.duox.dtunnel.grpc.pb.Revoked getRevoked() {
    if (kindCase_ == 2) {
       return (com.duox.dtunnel.grpc.pb.Revoked) kind_;
    }
    return com.duox.dtunnel.grpc.pb.Revoked.getDefaultInstance();
  }
  /**
   * <code>.duox.agent.v1.Revoked revoked = 2;</code>
   */
  @java.lang.Override
  public com.duox.dtunnel.grpc.pb.RevokedOrBuilder getRevokedOrBuilder() {
    if (kindCase_ == 2) {
       return (com.duox.dtunnel.grpc.pb.Revoked) kind_;
    }
    return com.duox.dtunnel.grpc.pb.Revoked.getDefaultInstance();
  }

  public static final int ACK_FIELD_NUMBER = 3;
  /**
   * <code>.duox.agent.v1.HeartbeatAck ack = 3;</code>
   * @return Whether the ack field is set.
   */
  @java.lang.Override
  public boolean hasAck() {
    return kindCase_ == 3;
  }
  /**
   * <code>.duox.agent.v1.HeartbeatAck ack = 3;</code>
   * @return The ack.
   */
  @java.lang.Override
  public com.duox.dtunnel.grpc.pb.HeartbeatAck getAck() {
    if (kindCase_ == 3) {
       return (com.duox.dtunnel.grpc.pb.HeartbeatAck) kind_;
    }
    return com.duox.dtunnel.grpc.pb.HeartbeatAck.getDefaultInstance();
  }
  /**
   * <code>.duox.agent.v1.HeartbeatAck ack = 3;</code>
   */
  @java.lang.Override
  public com.duox.dtunnel.grpc.pb.HeartbeatAckOrBuilder getAckOrBuilder() {
    if (kindCase_ == 3) {
       return (com.duox.dtunnel.grpc.pb.HeartbeatAck) kind_;
    }
    return com.duox.dtunnel.grpc.pb.HeartbeatAck.getDefaultInstance();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (kindCase_ == 1) {
      output.writeMessage(1, (com.duox.dtunnel.grpc.pb.ConfigPush) kind_);
    }
    if (kindCase_ == 2) {
      output.writeMessage(2, (com.duox.dtunnel.grpc.pb.Revoked) kind_);
    }
    if (kindCase_ == 3) {
      output.writeMessage(3, (com.duox.dtunnel.grpc.pb.HeartbeatAck) kind_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (kindCase_ == 1) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, (com.duox.dtunnel.grpc.pb.ConfigPush) kind_);
    }
    if (kindCase_ == 2) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, (com.duox.dtunnel.grpc.pb.Revoked) kind_);
    }
    if (kindCase_ == 3) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, (com.duox.dtunnel.grpc.pb.HeartbeatAck) kind_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.duox.dtunnel.grpc.pb.ServerMessage)) {
      return super.equals(obj);
    }
    com.duox.dtunnel.grpc.pb.ServerMessage other = (com.duox.dtunnel.grpc.pb.ServerMessage) obj;

    if (!getKindCase().equals(other.getKindCase())) return false;
    switch (kindCase_) {
      case 1:
        if (!getConfig()
            .equals(other.getConfig())) return false;
        break;
      case 2:
        if (!getRevoked()
            .equals(other.getRevoked())) return false;
        break;
      case 3:
        if (!getAck()
            .equals(other.getAck())) return false;
        break;
      case 0:
      default:
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    switch (kindCase_) {
      case 1:
        hash = (37 * hash) + CONFIG_FIELD_NUMBER;
        hash = (53 * hash) + getConfig().hashCode();
        break;
      case 2:
        hash = (37 * hash) + REVOKED_FIELD_NUMBER;
        hash = (53 * hash) + getRevoked().hashCode();
        break;
      case 3:
        hash = (37 * hash) + ACK_FIELD_NUMBER;
        hash = (53 * hash) + getAck().hashCode();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.duox.dtunnel.grpc.pb.ServerMessage parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.duox.dtunnel.grpc.pb.ServerMessage parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.duox.dtunnel.grpc.pb.ServerMessage parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.duox.dtunnel.grpc.pb.ServerMessage parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.duox.dtunnel.grpc.pb.ServerMessage parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.duox.dtunnel.grpc.pb.ServerMessage parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.duox.dtunnel.grpc.pb.ServerMessage parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.duox.dtunnel.grpc.pb.ServerMessage parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.duox.dtunnel.grpc.pb.ServerMessage parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.duox.dtunnel.grpc.pb.ServerMessage parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.duox.dtunnel.grpc.pb.ServerMessage parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.duox.dtunnel.grpc.pb.ServerMessage parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.duox.dtunnel.grpc.pb.ServerMessage prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Server -&gt; agent on the Control stream.
   * </pre>
   *
   * Protobuf type {@code duox.agent.v1.ServerMessage}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:duox.agent.v1.ServerMessage)
      com.duox.dtunnel.grpc.pb.ServerMessageOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.duox.dtunnel.grpc.pb.AgentProto.internal_static_duox_agent_v1_ServerMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.duox.dtunnel.grpc.pb.AgentProto.internal_static_duox_agent_v1_ServerMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.duox.dtunnel.grpc.pb.ServerMessage.class, com.duox.dtunnel.grpc.pb.ServerMessage.Builder.class);
    }

    // Construct using com.duox.dtunnel.grpc.pb.ServerMessage.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (configBuilder_ != null) {
        configBuilder_.clear();
      }
      if (revokedBuilder_ != null) {
        revokedBuilder_.clear();
      }
      if (ackBuilder_ != null) {
        ackBuilder_.clear();
      }
      kindCase_ = 0;
      kind_ = null;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.duox.dtunnel.grpc.pb.AgentProto.internal_static_duox_agent_v1_ServerMessage_descriptor;
    }

    @java.lang.Override
    public com.duox.dtunnel.grpc.pb.ServerMessage getDefaultInstanceForType() {
      return com.duox.dtunnel.grpc.pb.ServerMessage.getDefaultInstance();
    }

    @java.lang.Override
    public com.duox.dtunnel.grpc.pb.ServerMessage build() {
      com.duox.dtunnel.grpc.pb.ServerMessage result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.duox.dtunnel.grpc.pb.ServerMessage buildPartial() {
      com.duox.dtunnel.grpc.pb.ServerMessage result = new com.duox.dtunnel.grpc.pb.ServerMessage(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      buildPartialOneofs(result);
      onBuilt();
      return result;
    }

    private void buildPartial0(com.duox.dtunnel.grpc.pb.ServerMessage result) {
      int from_bitField0_ = bitField0_;
    }

    private void buildPartialOneofs(com.duox.dtunnel.grpc.pb.ServerMessage result) {
      result.kindCase_ = kindCase_;
      result.kind_ = this.kind_;
      if (kindCase_ == 1 &&
          configBuilder_ != null) {
        result.kind_ = configBuilder_.build();
      }
      if (kindCase_ == 2 &&
          revokedBuilder_ != null) {
        result.kind_ = revokedBuilder_.build();
      }
      if (kindCase_ == 3 &&
          ackBuilder_ != null) {
        result.kind_ = ackBuilder_.build();
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.duox.dtunnel.grpc.pb.ServerMessage) {
        return mergeFrom((com.duox.dtunnel.grpc.pb.ServerMessage)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.duox.dtunnel.grpc.pb.ServerMessage other) {
      if (other == com.duox.dtunnel.grpc.pb.ServerMessage.getDefaultInstance()) return this;
      switch (other.getKindCase()) {
        case CONFIG: {
          mergeConfig(other.getConfig());
          break;
        }
        case REVOKED: {
          mergeRevoked(other.getRevoked());
          break;
        }
        case ACK: {
          mergeAck(other.getAck());
          break;
        }
        case KIND_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  getConfigFieldBuilder().getBuilder(),
                  extensionRegistry);
              kindCase_ = 1;
              break;
            } // case 10
            case 18: {
              input.readMessage(
                  getRevokedFieldBuilder().getBuilder(),
                  extensionRegistry);
              kindCase_ = 2;
              break;
            } // case 18
            case 26: {
              input.readMessage(
                  getAckFieldBuilder().getBuilder(),
                  extensionRegistry);
              kindCase_ = 3;
              break;
            } // case 26
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int kindCase_ = 0;
    private java.lang.Object kind_;
    public KindCase
        getKindCase() {
      return KindCase.forNumber(
          kindCase_);
    }

    public Builder clearKind() {
      kindCase_ = 0;
      kind_ = null;
      onChanged();
      return this;
    }

    private int bitField0_;

    private com.google.protobuf.SingleFieldBuilder<
        com.duox.dtunnel.grpc.pb.ConfigPush, com.duox.dtunnel.grpc.pb.ConfigPush.Builder, com.duox.dtunnel.grpc.pb.ConfigPushOrBuilder> configBuilder_;
    /**
     * <code>.duox.agent.v1.ConfigPush config = 1;</code>
     * @return Whether the config field is set.
     */
    @java.lang.Override
    public boolean hasConfig() {
      return kindCase_ == 1;
    }
    /**
     * <code>.duox.agent.v1.ConfigPush config = 1;</code>
     * @return The config.
     */
    @java.lang.Override
    public com.duox.dtunnel.grpc.pb.ConfigPush getConfig() {
      if (configBuilder_ == null) {
        if (kindCase_ == 1) {
          return (com.duox.dtunnel.grpc.pb.ConfigPush) kind_;
        }
        return com.duox.dtunnel.grpc.pb.ConfigPush.getDefaultInstance();
      } else {
        if (kindCase_ == 1) {
          return configBuilder_.getMessage();
        }
        return com.duox.dtunnel.grpc.pb.ConfigPush.getDefaultInstance();
      }
    }
    /**
     * <code>.duox.agent.v1.ConfigPush config = 1;</code>
     */
    public Builder setConfig(com.duox.dtunnel.grpc.pb.ConfigPush value) {
      if (configBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        kind_ = value;
        onChanged();
      } else {
        configBuilder_.setMessage(value);
      }
      kindCase_ = 1;
      return this;
    }
    /**
     * <code>.duox.agent.v1.ConfigPush config = 1;</code>
     */
    public Builder setConfig(
        com.duox.dtunnel.grpc.pb.ConfigPush.Builder builderForValue) {
      if (configBuilder_ == null) {
        kind_ = builderForValue.build();
        onChanged();
      } else {
        configBuilder_.setMessage(builderForValue.build());
      }
      kindCase_ = 1;
      return this;
    }
    /**
     * <code>.duox.agent.v1.ConfigPush config = 1;</code>
     */
    public Builder mergeConfig(com.duox.dtunnel.grpc.pb.ConfigPush value) {
      if (configBuilder_ == null) {
        if (kindCase_ == 1 &&
            kind_ != com.duox.dtunnel.grpc.pb.ConfigPush.getDefaultInstance()) {
          kind_ = com.duox.dtunnel.grpc.pb.ConfigPush.newBuilder((com.duox.dtunnel.grpc.pb.ConfigPush) kind_)
              .mergeFrom(value).buildPartial();
        } else {
          kind_ = value;
        }
        onChanged();
      } else {
        if (kindCase_ == 1) {
          configBuilder_.mergeFrom(value);
        } else {
          configBuilder_.setMessage(value);
        }
      }
      kindCase_ = 1;
      return this;
    }
    /**
     * <code>.duox.agent.v1.ConfigPush config = 1;</code>
     */
    public Builder clearConfig() {
      if (configBuilder_ == null) {
        if (kindCase_ == 1) {
          kindCase_ = 0;
          kind_ = null;
          onChanged();
        }
      } else {
        if (kindCase_ == 1) {
          kindCase_ = 0;
          kind_ = null;
        }
        configBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.duox.agent.v1.ConfigPush config = 1;</code>
     */
    public com.duox.dtunnel.grpc.pb.ConfigPush.Builder getConfigBuilder() {
      return getConfigFieldBuilder().getBuilder();
    }
    /**
     * <code>.duox.agent.v1.ConfigPush config = 1;</code>
     */
    @java.lang.Override
    public com.duox.dtunnel.grpc.pb.ConfigPushOrBuilder getConfigOrBuilder() {
      if ((kindCase_ == 1) && (configBuilder_ != null)) {
        return configBuilder_.getMessageOrBuilder();
      } else {
        if (kindCase_ == 1) {
          return (com.duox.dtunnel.grpc.pb.ConfigPush) kind_;
        }
        return com.duox.dtunnel.grpc.pb.ConfigPush.getDefaultInstance();
      }
    }
    /**
     * <code>.duox.agent.v1.ConfigPush config = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.duox.dtunnel.grpc.pb.ConfigPush, com.duox.dtunnel.grpc.pb.ConfigPush.Builder, com.duox.dtunnel.grpc.pb.ConfigPushOrBuilder> 
        getConfigFieldBuilder() {
      if (configBuilder_ == null) {
        if (!(kindCase_ == 1)) {
          kind_ = com.duox.dtunnel.grpc.pb.ConfigPush.getDefaultInstance();
        }
        configBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.duox.dtunnel.grpc.pb.ConfigPush, com.duox.dtunnel.grpc.pb.ConfigPush.Builder, com.duox.dtunnel.grpc.pb.ConfigPushOrBuilder>(
                (com.duox.dtunnel.grpc.pb.ConfigPush) kind_,
                getParentForChildren(),
                isClean());
        kind_ = null;
      }
      kindCase_ = 1;
      onChanged();
      return configBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilder<
        com.duox.dtunnel.grpc.pb.Revoked, com.duox.dtunnel.grpc.pb.Revoked.Builder, com.duox.dtunnel.grpc.pb.RevokedOrBuilder> revokedBuilder_;
    /**
     * <code>.duox.agent.v1.Revoked revoked = 2;</code>
     * @return Whether the revoked field is set.
     */
    @java.lang.Override
    public boolean hasRevoked() {
      return kindCase_ == 2;
    }
    /**
     * <code>.duox.agent.v1.Revoked revoked = 2;</code>
     * @return The revoked.
     */
    @java.lang.Override
    public com.duox.dtunnel.grpc.pb.Revoked getRevoked() {
      if (revokedBuilder_ == null) {
        if (kindCase_ == 2) {
          return (com.duox.dtunnel.grpc.pb.Revoked) kind_;
        }
        return com.duox.dtunnel.grpc.pb.Revoked.getDefaultInstance();
      } else {
        if (kindCase_ == 2) {
          return revokedBuilder_.getMessage();
        }
        return com.duox.dtunnel.grpc.pb.Revoked.getDefaultInstance();
      }
    }
    /**
     * <code>.duox.agent.v1.Revoked revoked = 2;</code>
     */
    public Builder setRevoked(com.duox.dtunnel.grpc.pb.Revoked value) {
      if (revokedBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        kind_ = value;
        onChanged();
      } else {
        revokedBuilder_.setMessage(value);
      }
      kindCase_ = 2;
      return this;
    }
    /**
     * <code>.duox.agent.v1.Revoked revoked = 2;</code>
     */
    public Builder setRevoked(
        com.duox.dtunnel.grpc.pb.Revoked.Builder builderForValue) {
      if (revokedBuilder_ == null) {
        kind_ = builderForValue.build();
        onChanged();
      } else {
        revokedBuilder_.setMessage(builderForValue.build());
      }
      kindCase_ = 2;
      return this;
    }
    /**
     * <code>.duox.agent.v1.Revoked revoked = 2;</code>
     */
    public Builder mergeRevoked(com.duox.dtunnel.grpc.pb.Revoked value) {
      if (revokedBuilder_ == null) {
        if (kindCase_ == 2 &&
            kind_ != com.duox.dtunnel.grpc.pb.Revoked.getDefaultInstance()) {
          kind_ = com.duox.dtunnel.grpc.pb.Revoked.newBuilder((com.duox.dtunnel.grpc.pb.Revoked) kind_)
              .mergeFrom(value).buildPartial();
        } else {
          kind_ = value;
        }
        onChanged();
      } else {
        if (kindCase_ == 2) {
          revokedBuilder_.mergeFrom(value);
        } else {
          revokedBuilder_.setMessage(value);
        }
      }
      kindCase_ = 2;
      return this;
    }
    /**
     * <code>.duox.agent.v1.Revoked revoked = 2;</code>
     */
    public Builder clearRevoked() {
      if (revokedBuilder_ == null) {
        if (kindCase_ == 2) {
          kindCase_ = 0;
          kind_ = null;
          onChanged();
        }
      } else {
        if (kindCase_ == 2) {
          kindCase_ = 0;
          kind_ = null;
        }
        revokedBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.duox.agent.v1.Revoked revoked = 2;</code>
     */
    public com.duox.dtunnel.grpc.pb.Revoked.Builder getRevokedBuilder() {
      return getRevokedFieldBuilder().getBuilder();
    }
    /**
     * <code>.duox.agent.v1.Revoked revoked = 2;</code>
     */
    @java.lang.Override
    public com.duox.dtunnel.grpc.pb.RevokedOrBuilder getRevokedOrBuilder() {
      if ((kindCase_ == 2) && (revokedBuilder_ != null)) {
        return revokedBuilder_.getMessageOrBuilder();
      } else {
        if (kindCase_ == 2) {
          return (com.duox.dtunnel.grpc.pb.Revoked) kind_;
        }
        return com.duox.dtunnel.grpc.pb.Revoked.getDefaultInstance();
      }
    }
    /**
     * <code>.duox.agent.v1.Revoked revoked = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.duox.dtunnel.grpc.pb.Revoked, com.duox.dtunnel.grpc.pb.Revoked.Builder, com.duox.dtunnel.grpc.pb.RevokedOrBuilder> 
        getRevokedFieldBuilder() {
      if (revokedBuilder_ == null) {
        if (!(kindCase_ == 2)) {
          kind_ = com.duox.dtunnel.grpc.pb.Revoked.getDefaultInstance();
        }
        revokedBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.duox.dtunnel.grpc.pb.Revoked, com.duox.dtunnel.grpc.pb.Revoked.Builder, com.duox.dtunnel.grpc.pb.RevokedOrBuilder>(
                (com.duox.dtunnel.grpc.pb.Revoked) kind_,
                getParentForChildren(),
                isClean());
        kind_ = null;
      }
      kindCase_ = 2;
      onChanged();
      return revokedBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilder<
        com.duox.dtunnel.grpc.pb.HeartbeatAck, com.duox.dtunnel.grpc.pb.HeartbeatAck.Builder, com.duox.dtunnel.grpc.pb.HeartbeatAckOrBuilder> ackBuilder_;
    /**
     * <code>.duox.agent.v1.HeartbeatAck ack = 3;</code>
     * @return Whether the ack field is set.
     */
    @java.lang.Override
    public boolean hasAck() {
      return kindCase_ == 3;
    }
    /**
     * <code>.duox.agent.v1.HeartbeatAck ack = 3;</code>
     * @return The ack.
     */
    @java.lang.Override
    public com.duox.dtunnel.grpc.pb.HeartbeatAck getAck() {
      if (ackBuilder_ == null) {
        if (kindCase_ == 3) {
          return (com.duox.dtunnel.grpc.pb.HeartbeatAck) kind_;
        }
        return com.duox.dtunnel.grpc.pb.HeartbeatAck.getDefaultInstance();
      } else {
        if (kindCase_ == 3) {
          return ackBuilder_.getMessage();
        }
        return com.duox.dtunnel.grpc.pb.HeartbeatAck.getDefaultInstance();
      }
    }
    /**
     * <code>.duox.agent.v1.HeartbeatAck ack = 3;</code>
     */
    public Builder setAck(com.duox.dtunnel.grpc.pb.HeartbeatAck value) {
      if (ackBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        kind_ = value;
        onChanged();
      } else {
        ackBuilder_.setMessage(value);
      }
      kindCase_ = 3;
      return this;
    }
    /**
     * <code>.duox.agent.v1.HeartbeatAck ack = 3;</code>
     */
    public Builder setAck(
        com.duox.dtunnel.grpc.pb.HeartbeatAck.Builder builderForValue) {
      if (ackBuilder_ == null) {
        kind_ = builderForValue.build();
        onChanged();
      } else {
        ackBuilder_.setMessage(builderForValue.build());
      }
      kindCase_ = 3;
      return this;
    }
    /**
     * <code>.duox.agent.v1.HeartbeatAck ack = 3;</code>
     */
    public Builder mergeAck(com.duox.dtunnel.grpc.pb.HeartbeatAck value) {
      if (ackBuilder_ == null) {
        if (kindCase_ == 3 &&
            kind_ != com.duox.dtunnel.grpc.pb.HeartbeatAck.getDefaultInstance()) {
          kind_ = com.duox.dtunnel.grpc.pb.HeartbeatAck.newBuilder((com.duox.dtunnel.grpc.pb.HeartbeatAck) kind_)
              .mergeFrom(value).buildPartial();
        } else {
          kind_ = value;
        }
        onChanged();
      } else {
        if (kindCase_ == 3) {
          ackBuilder_.mergeFrom(value);
        } else {
          ackBuilder_.setMessage(value);
        }
      }
      kindCase_ = 3;
      return this;
    }
    /**
     * <code>.duox.agent.v1.HeartbeatAck ack = 3;</code>
     */
    public Builder clearAck() {
      if (ackBuilder_ == null) {
        if (kindCase_ == 3) {
          kindCase_ = 0;
          kind_ = null;
          onChanged();
        }
      } else {
        if (kindCase_ == 3) {
          kindCase_ = 0;
          kind_ = null;
        }
        ackBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.duox.agent.v1.HeartbeatAck ack = 3;</code>
     */
    public com.duox.dtunnel.grpc.pb.HeartbeatAck.Builder getAckBuilder() {
      return getAckFieldBuilder().getBuilder();
    }
    /**
     * <code>.duox.agent.v1.HeartbeatAck ack = 3;</code>
     */
    @java.lang.Override
    public com.duox.dtunnel.grpc.pb.HeartbeatAckOrBuilder getAckOrBuilder() {
      if ((kindCase_ == 3) && (ackBuilder_ != null)) {
        return ackBuilder_.getMessageOrBuilder();
      } else {
        if (kindCase_ == 3) {
          return (com.duox.dtunnel.grpc.pb.HeartbeatAck) kind_;
        }
        return com.duox.dtunnel.grpc.pb.HeartbeatAck.getDefaultInstance();
      }
    }
    /**
     * <code>.duox.agent.v1.HeartbeatAck ack = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.duox.dtunnel.grpc.pb.HeartbeatAck, com.duox.dtunnel.grpc.pb.HeartbeatAck.Builder, com.duox.dtunnel.grpc.pb.HeartbeatAckOrBuilder> 
        getAckFieldBuilder() {
      if (ackBuilder_ == null) {
        if (!(kindCase_ == 3)) {
          kind_ = com.duox.dtunnel.grpc.pb.HeartbeatAck.getDefaultInstance();
        }
        ackBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.duox.dtunnel.grpc.pb.HeartbeatAck, com.duox.dtunnel.grpc.pb.HeartbeatAck.Builder, com.duox.dtunnel.grpc.pb.HeartbeatAckOrBuilder>(
                (com.duox.dtunnel.grpc.pb.HeartbeatAck) kind_,
                getParentForChildren(),
                isClean());
        kind_ = null;
      }
      kindCase_ = 3;
      onChanged();
      return ackBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:duox.agent.v1.ServerMessage)
  }

  // @@protoc_insertion_point(class_scope:duox.agent.v1.ServerMessage)
  private static final com.duox.dtunnel.grpc.pb.ServerMessage DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.duox.dtunnel.grpc.pb.ServerMessage();
  }

  public static com.duox.dtunnel.grpc.pb.ServerMessage getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ServerMessage>
      PARSER = new com.google.protobuf.AbstractParser<ServerMessage>() {
    @java.lang.Override
    public ServerMessage parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ServerMessage> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ServerMessage> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.duox.dtunnel.grpc.pb.ServerMessage getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

