// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: duox/agent/v1/agent.proto
// Protobuf Java Version: 4.27.2

package com.duox.dtunnel.grpc.pb;

public interface TunnelReportOrBuilder extends
    // @@protoc_insertion_point(interface_extends:duox.agent.v1.TunnelReport)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string tunnel_id = 1;</code>
   * @return The tunnelId.
   */
  java.lang.String getTunnelId();
  /**
   * <code>string tunnel_id = 1;</code>
   * @return The bytes for tunnelId.
   */
  com.google.protobuf.ByteString
      getTunnelIdBytes();

  /**
   * <pre>
   * RUNNING | STOPPED | ERROR
   * </pre>
   *
   * <code>string status = 2;</code>
   * @return The status.
   */
  java.lang.String getStatus();
  /**
   * <pre>
   * RUNNING | STOPPED | ERROR
   * </pre>
   *
   * <code>string status = 2;</code>
   * @return The bytes for status.
   */
  com.google.protobuf.ByteString
      getStatusBytes();
}
