// detail.md §4: agent <-> control-plane channel. REST is the MVP transport;
// this gRPC service is the Phase-2 swap (push-config + sub-second revocation).
// It is deliberately narrow: registration stays unary, and the steady-state
// channel is ONE bidirectional stream carrying desired-state pushes,
// revocation signals, and agent heartbeats.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             v5.27.2
// source: duox/agent/v1/agent.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	AgentService_Register_FullMethodName = "/duox.agent.v1.AgentService/Register"
	AgentService_Control_FullMethodName  = "/duox.agent.v1.AgentService/Control"
)

// AgentServiceClient is the client API for AgentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AgentServiceClient interface {
	// First-run device registration (detail.md §6). Unary, mirrors the REST
	// /agent/v1/register contract.
	Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error)
	// Steady-state control stream. The agent opens it once (authenticated by its
	// device token in the Hello message) and keeps it open:
	//
	//	server -> agent: ConfigPush on every desired-state version bump,
	//	                 Revoked the instant an admin revokes the device,
	//	                 HeartbeatAck for each heartbeat;
	//	agent  -> server: Hello (handshake), then periodic Heartbeat.
	//
	// This is what bounds revocation latency to milliseconds instead of the
	// heartbeat interval (detail.md §4).
	Control(ctx context.Context, opts ...grpc.CallOption) (AgentService_ControlClient, error)
}

type agentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentServiceClient(cc grpc.ClientConnInterface) AgentServiceClient {
	return &agentServiceClient{cc}
}

func (c *agentServiceClient) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterResponse)
	err := c.cc.Invoke(ctx, AgentService_Register_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) Control(ctx context.Context, opts ...grpc.CallOption) (AgentService_ControlClient, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AgentService_ServiceDesc.Streams[0], AgentService_Control_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &agentServiceControlClient{ClientStream: stream}
	return x, nil
}

type AgentService_ControlClient interface {
	Send(*AgentMessage) error
	Recv() (*ServerMessage, error)
	grpc.ClientStream
}

type agentServiceControlClient struct {
	grpc.ClientStream
}

func (x *agentServiceControlClient) Send(m *AgentMessage) error {
	return x.ClientStream.SendMsg(m)
}

func (x *agentServiceControlClient) Recv() (*ServerMessage, error) {
	m := new(ServerMessage)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// AgentServiceServer is the server API for AgentService service.
// All implementations must embed UnimplementedAgentServiceServer
// for forward compatibility
type AgentServiceServer interface {
	// First-run device registration (detail.md §6). Unary, mirrors the REST
	// /agent/v1/register contract.
	Register(context.Context, *RegisterRequest) (*RegisterResponse, error)
	// Steady-state control stream. The agent opens it once (authenticated by its
	// device token in the Hello message) and keeps it open:
	//
	//	server -> agent: ConfigPush on every desired-state version bump,
	//	                 Revoked the instant an admin revokes the device,
	//	                 HeartbeatAck for each heartbeat;
	//	agent  -> server: Hello (handshake), then periodic Heartbeat.
	//
	// This is what bounds revocation latency to milliseconds instead of the
	// heartbeat interval (detail.md §4).
	Control(AgentService_ControlServer) error
	mustEmbedUnimplementedAgentServiceServer()
}

// UnimplementedAgentServiceServer must be embedded to have forward compatible implementations.
type UnimplementedAgentServiceServer struct {
}

func (UnimplementedAgentServiceServer) Register(context.Context, *RegisterRequest) (*RegisterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Register not implemented")
}
func (UnimplementedAgentServiceServer) Control(AgentService_ControlServer) error {
	return status.Errorf(codes.Unimplemented, "method Control not implemented")
}
func (UnimplementedAgentServiceServer) mustEmbedUnimplementedAgentServiceServer() {}

// UnsafeAgentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentServiceServer will
// result in compilation errors.
type UnsafeAgentServiceServer interface {
	mustEmbedUnimplementedAgentServiceServer()
}

func RegisterAgentServiceServer(s grpc.ServiceRegistrar, srv AgentServiceServer) {
	s.RegisterService(&AgentService_ServiceDesc, srv)
}

func _AgentService_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_Register_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).Register(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_Control_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AgentServiceServer).Control(&agentServiceControlServer{ServerStream: stream})
}

type AgentService_ControlServer interface {
	Send(*ServerMessage) error
	Recv() (*AgentMessage, error)
	grpc.ServerStream
}

type agentServiceControlServer struct {
	grpc.ServerStream
}

func (x *agentServiceControlServer) Send(m *ServerMessage) error {
	return x.ServerStream.SendMsg(m)
}

func (x *agentServiceControlServer) Recv() (*AgentMessage, error) {
	m := new(AgentMessage)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// AgentService_ServiceDesc is the grpc.ServiceDesc for AgentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AgentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "duox.agent.v1.AgentService",
	HandlerType: (*AgentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _AgentService_Register_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Control",
			Handler:       _AgentService_Control_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "duox/agent/v1/agent.proto",
}
