package com.duox.dtunnel.domain;

/** detail.md §2: AVAILABLE→RESERVED→ALLOCATED→ACTIVE→EXPIRED_PENDING_RELEASE→RELEASED/DISABLED */
public enum PortStatus { AVAILABLE, RESERVED, ALLOCATED, ACTIVE, EXPIRED_PENDING_RELEASE, RELEASED, DISABLED }
