package com.duox.dtunnel.domain;

/** detail.md §2: CREATED→CONFIGURED→STARTING→ACTIVE→STOPPING→STOPPED (+ERROR, EXPIRING→EXPIRED) */
public enum TunnelStatus { CREATED, CONFIGURED, STARTING, ACTIVE, STOPPING, STOPPED, ERROR, EXPIRING, EXPIRED }
